### ISSUE TITLE
BUG: Tests fail on windows environments

### ISSUE THREAD

**Issue by TGTGamer** [zenstackhq/zenstack#1020]
**Description and expected behavior**
Not to fail. 

```cmd
pnpm test          

> zenstack-monorepo@1.9.0 test Z:\zenstack
> ZENSTACK_TEST=1 pnpm -r run test --silent --forceExit

'ZENSTACK_TEST' is not recognized as an internal or external command,
operable program or batch file.
 ELIFECYCLE  Test failed. See above for more details.
```

**Suggestion**

Add development containers to support codespaces and docker environments without need to manually configure for each machine.

**Comment by ymc9** [comment]
Hi @TGTGamer , my apologies I always forget about Windows 😅

I believe `ZENSTACK_TEST` is the only setting needed for now. Let me refactor and turn it into a jest config.

The other bigger thing is that some tests also rely on a local postgres instance. Having it configured in devcontainer sounds like a good idea.

**Comment by ymc9** [comment]
Hi @TGTGamer , I've moved the env variable to jest config and removed it from the npm script. Could you merge and try again?

**Comment by TGTGamer** [comment]
Will try to schedule this in shortly, in the middle of having a OS identity break as I found something else which I wanted to use which is Linux only and it finally pushed me over the edge to make the switch to linux I've been planning for months :)
