### ISSUE TITLE
@password does not encrypt password field on 2.0.0-alpha1

### ISSUE THREAD

**Issue by sarioglu** [zenstackhq/zenstack#1055]
**Description and expected behavior**
`@password` descriptor works as expected on 1.9.0 and encrypts passwords when a new user created. But it does nothing on 2.0.0 and password is stored unencrypted.

**Environment (please complete the following information):**

-   ZenStack version: [e.g., 2.0.0-alpha.1]
-   Prisma version: [e.g., 5.9.1]
-   Database type: [e.g. Mysql]

**Comment by ymc9** [comment]
> **Description and expected behavior** `@password` descriptor works as expected on 1.9.0 and encrypts passwords when a new user created. But it does nothing on 2.0.0 and password is stored unencrypted.
> 
> **Environment (please complete the following information):**
> 
> * ZenStack version: [e.g., 2.0.0-alpha.1]
> * Prisma version: [e.g., 5.9.1]
> * Database type: [e.g. Mysql]

Hi @sarioglu , I just tried v2 alpha.1 and it seems `@password` is effective. Do you mind sharing your model and code snippet?

**Comment by ymc9** [comment]
Closing for now.
