### ISSUE TITLE
[Question] Clarification on Lack of Specific Prisma Version as Peer Dependency

### ISSUE THREAD

**Issue by iamfj** [zenstackhq/zenstack#1084]
Hi ZenStack team,

I've been exploring your repository and noticed that there is no specific version set for Prisma as a peer dependency. I'm curious about the rationale behind this decision.

Given the rapid development and frequent updates of Prisma, I'm concerned about compatibility issues between ZenStack and future versions of Prisma. Typically, libraries that extend or enhance the functionality of other libraries specify compatible versions to prevent conflicts and ensure stable integration.

Could you please clarify the following points:
1. Is ZenStack designed to be compatible with any future updates of Prisma, or is there a range of versions that are known to work without issues?
2. If ZenStack is intended to work with any version of Prisma, how do you ensure compatibility with future updates, especially considering the potential for breaking changes?
3. Would it be possible to define a peer dependency version range for Prisma to help users avoid compatibility issues?

I believe that setting a specific version or range for Prisma as a peer dependency could greatly benefit users by providing clearer guidelines and preventing potential integration problems.

Thank you for your time and effort in maintaining this project. I look forward to your response and clarification.

Best regards,
Fabian

**Comment by ymc9** [comment]
Hi @iamfj , thanks for bringing this up. Yes, I believe a peer dependency on Prisma is a great idea. There's no specific reason why it's not there. It just hasn't been done yet 😄.

ZenStack now supports all Prisma versions >= 4.8.0. There's a runtime check for it. Yes, we actively watch Prisma changes and intend to support all future versions (with a short delay). The minimum supported version will change to prevent version-specific code from growing infinitely. The plan for V2 is to support V5+.

The development of V1 track is ramping down. I think we can add proper peer dependencies starting from V2. Does that work for you?

**Comment by iamfj** [comment]
Thanks!
