### ISSUE TITLE
[Feature Request] VSCode extension - formatting zmodel file not same style as Prisma VSCode extension format

### ISSUE THREAD

**Issue by MariusVB** [zenstackhq/zenstack#1092]
**Is your feature request related to a problem? Please describe.**
It seems the format rules of the Zenstack extension are not the same as the Prisma extension. The Prisma extension makes field names, data types and attributes line up, whereas Zenstack extension moves them all as far left as possible. Everytime I save the zmodel file, I have to run `Save without formatting`...

**Describe the solution you'd like**
Follow the same rules as the Prisma schema formatter. Names, data types and attributes should line up within the same model.

**Describe alternatives you've considered**
Run `Save without formatting` each time and take care of the indentation yourself...

**Additional context**

Actual result of Zenstack zmodel format:
![image](https://github.com/zenstackhq/zenstack/assets/24921111/0483002b-9d36-4d6f-8fa9-28cbf8371341)

Expected result like Prisma format:
![image](https://github.com/zenstackhq/zenstack/assets/24921111/7f3c5d3c-a0b6-43e0-aad0-6d62ab520f05)

*EDIT*
The format could even be improved by also lining up field-level policies. E.g.:
![image](https://github.com/zenstackhq/zenstack/assets/24921111/152e819c-184b-4d2d-9974-b5dd5c2e718e)

It might result in very long lines, but perhaps a multi-line formatting rule could be made then?

**Comment by ymc9** [comment]
Hi @MariusVB , there's an exiting request for it here: https://github.com/zenstackhq/zenstack/issues/885

**Comment by ymc9** [comment]
Fixed in 2.0.0-beta.13
