### ISSUE TITLE
Type errors with nested create/connects in client with polymorphic models

### ISSUE THREAD

**Issue by andrewkucz** [zenstackhq/zenstack#1135]
**Description and expected behavior**

Hello again,

For a typical prisma schema, when you are doing a nested create of a related object, you don't need to specify the key of the record from which you are creating (parent) because it is implied.

Consider the following schema where a person can have multiple attachments (1-many):
```
model Attachment {
  id          String  @id @default(cuid()) 
  url         String
  personId      String
  person        Person        @relation(fields: [personId], references: [id], onUpdate: NoAction)
}

model Person {
  id      String          @id @default(cuid()) 
  name    String
  age Int?   
  attachments Attachment[]
}
```

The following is a valid create statement with nested attachment creation, notice `personId` doesn't need to be specified because the created attachment will use the id of the person being created
```
await db.person.create({
	data: {
		name: "test",
		attachments: {
			create: {
				url: "https://...",
			},
		},
	},
});
```

Now consider the following zmodel: same schema but Person extends an "Entity" model (simplified for this example)
```
model Attachment {
  id          String  @id
  url         String
  entityId      String
  entity        Entity        @relation(fields: [entityId], references: [id], onUpdate: NoAction)
}

model Entity {

  id      String          @id @default(cuid()) 
  name    String
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt @default(now())
  
  attachments Attachment[]

  type String
  @@delegate(type)
}

model Person extends Entity {
  age Int?
}
```

The above create code now yields the following type error:
```
Type '{ url: string; }' is not assignable to type '(Without<AttachmentCreateWithoutDelegate_aux_personInput, AttachmentUncheckedCreateWithoutDelegate_aux_personInput> & AttachmentUncheckedCreateWithoutDelegate_aux_personInput) | (Without<...> & AttachmentCreateWithoutDelegate_aux_personInput) | AttachmentCreateWithoutDelegate_aux_personInput[] | AttachmentUncheckedC...'.
```

It seems to want the entityId (the foreign key, previously "personId") to be specified despite that it shouldn't need it.

```
await db.person.create({
	data: {
		name: "test",
		attachments: {
      // ts error-
      create: 
        url: 'https://',
        // entityId: 'some ID Here?',
      }
		},
	},
});
```

Anyway, not sure if this is a limitation of Prisma or how polymorphism works internally but just thought I'd share.

As always, great work!

-Andrew

---

**Environment (please complete the following information):**

-   ZenStack version: 2.0.0-alpha.7
-   Prisma version: 5.11
-   Database type: postgresql

**Comment by ymc9** [comment]
Hi @andrewkucz , thanks for reporting this! Looks like a scenario not covered in the tests. I'll make a fix soon.

Thanks for trying out alpha and please keep the feedback coming!
