### ISSUE TITLE
Delegating models can't use `@@map()`

### ISSUE THREAD

**Issue by keanugrieves** [zenstackhq/zenstack#1167]
**Description and expected behavior**
Doing this throws an error when running `zenstack generate`:

```
model FileAsset {
  delegate_type String
  ...
  @@delegate(delegate_type)
  @@map("file_assets")
}

model ImageAsset extends FileAsset {
  ...
  @@map("image_assets")
}
```

...after generating the following in `schema.prisma`:

```
/// @@delegate(delegate_type)
model FileAsset {
    ...
    delegate_aux_imageAsset ImageAsset?

    @@map("file_assets")
}

model ImageAsset {
    ...
    delegate_aux_fileAsset FileAsset @relation(fields: [id], references: [id], onDelete: Cascade, onUpdate: Cascade)

    @@map("file_assets")
    @@map("image_assets")
}
```

**Screenshots**
![Screenshot 2024-03-20 at 1 25 28 PM](https://github.com/zenstackhq/zenstack/assets/51007475/9d946fb2-889f-4a68-81d9-5f1d14a461b5)

**Environment (please complete the following information):**

-   ZenStack version: 2.0.0-beta.1
-   Prisma version: 5.11.0
-   Database type: postgresql

**Comment by ymc9** [comment]
Great to see you here again @keanugrieves 😄. Good catch! The `@@map` attribute should be inherited.

**Comment by keanugrieves** [comment]
> Great to see you here again @keanugrieves 😄. Good catch! The `@@map` attribute should be inherited.

I never left! 😄 

Unless I'm misunderstanding something, the ideal behavior is that `@@map` **should not** be inherited, right? It's not a big deal except I'm using ZenStack within a schema that follows the plural snake naming conventions for tables.

**Comment by ymc9** [comment]
> > Great to see you here again @keanugrieves 😄. Good catch! The `@@map` attribute should be inherited.
> 
> I never left! 😄
> 
> Unless I'm misunderstanding something, the ideal behavior is that `@@map` **should not** be inherited, right? It's not a big deal except I'm using ZenStack in an organization that follows the plural snake naming conventions for tables.

Yes, sorry that I missed typing "not" in my original reply ... Will fix it soon.
