### ISSUE TITLE
zod types do not generate uuids with `@db.Uuid` attribute

### ISSUE THREAD

**Issue by sakgoyal** [zenstackhq/zenstack#1196]
**Description and expected behavior**
when using `@db.Uuid` attribute, zod types do not generate `string().uuid()`. it only generates `string()`. 

**Screenshots**
![image](https://github.com/zenstackhq/zenstack/assets/19929553/14031128-6680-4880-85f6-6e09cb892cef)
![image](https://github.com/zenstackhq/zenstack/assets/19929553/5b522f60-4f78-4e35-9a67-56db935bcece)

**Environment (please complete the following information):**
ZenStack version: v2

**Comment by ymc9** [comment]
Yes, this makes good sense. Would you be interested in making a PR?

**Comment by sakgoyal** [comment]
I am not familiar with the code unfortunately. I don't know how to do it. but I can take a look to try

**Comment by ymc9** [comment]
Thank you! I think the place of change should be here: https://github.com/zenstackhq/zenstack/blob/dfa6cb48680ef9aa48e6a56161bddb078100c3c0/packages/schema/src/plugins/zod/utils/schema-gen.ts#L154

You can access attributes from the `field` parameter (which is AST node parsed from ZModel). Let me know if you need more information.

**Comment by sakgoyal** [comment]
#1206 
test PR. not ready yet

**Comment by sakgoyal** [comment]
I think this is correct. I was having issues setting up the project so I just made the change in the github web editor. I hope that is the only change I need to make since

**Comment by ymc9** [comment]
Fixed in 1.12.1
