### ISSUE TITLE
[Feature Request] `@readonly` attributes

### ISSUE THREAD

**Issue by sakgoyal** [zenstackhq/zenstack#1197]
**Is your feature request related to a problem? Please describe.**
allow the schema to implement a `@readonly` attribute so we can set a static field on a model that is the same for all rows in a table (set a field to be a static string in the schema itself), (or allow it to be set on creation, but cannot be updated)

**Describe alternatives you've considered**
It is possible to use enums to set this value and use `@default`, but I do not want to be able to change this value. so, this is not possible right now.

**Comment by ymc9** [comment]
Hi @sakgoyal , do you think this can be achieved with field-level policy? Like:

```prisma
model Foo {
  ...
  readonlyField Int @deny('update', true)
}
```

**Comment by sakgoyal** [comment]
Will this work together with @default? if so, then yes.

**Comment by ymc9** [comment]
> Will this work together with @default? if so, then yes.

Yes, I believe so.

**Comment by sakgoyal** [comment]
#1208 
I know I closed this. but would you still consider this is a potential feature? it could just be a shorthand replacement for `@deny('update', true)` into just `@readonly`.
