### ISSUE TITLE
[Feature Request] Integration with Prisma Extensions

### ISSUE THREAD

**Issue by sakgoyal** [zenstackhq/zenstack#1200]
**Is your feature request related to a problem? Please describe.**
I am using several prisma extensions that modify the default prisma client and change the query section to add custom computed fields. how can I integrate this with zenstack?

**Comment by ymc9** [comment]
Hi @sakgoyal , could you check if this fresh new doc helps 😄?

https://zenstack.dev/docs/guides/client-extensions

**Comment by sakgoyal** [comment]
Oh perfect. Thank you. I didn't see this before
