### ISSUE TITLE
REST Handler requires id in the body while it already present on URL

### ISSUE THREAD

**Issue by vgarmash** [zenstackhq/zenstack#1222]
**Description and expected behavior**
It is confusing that we need to repeat the Id of the entity that we are updating by POST or PUT operations. I can provide one Id in URL and another in the body and the update is done to the object with Id in the Body while I assume the Id in the URL should be updated. . If I omit the id in the body, then I get error 404.

**Screenshots**
![image](https://github.com/zenstackhq/zenstack/assets/1226001/b99bde8e-ebbd-425a-b5cc-0d363d6e6e70)

**Environment (please complete the following information):**

-   ZenStack version: 1.12.0
-   Prisma version: 5.12.1
-   Database type: Postgresql

**Comment by ymc9** [comment]
Hi @vgarmash , thanks for reporting this. I understand it feels redundant, but currently ZenStack's RESTful API follows the JSON:API specification: https://jsonapi.org/format/#crud-updating. The "id" field in the payload is required.
