### ISSUE TITLE
Issue using @@index with @@delegate

### ISSUE THREAD

**Issue by acdifran** [zenstackhq/zenstack#1243]
**Description and expected behavior**
Any `@@index` attribute is copied over from the delegate model when using `@@delegate`, which causes an error in `schema.prisma` for referencing an unknown field.

**Screenshots**
<img width="631" alt="Screenshot 2024-04-11 at 5 44 09 PM" src="https://github.com/zenstackhq/zenstack/assets/25591626/4bf272f0-3549-4b2d-bb4c-9012952c161f">
<img width="1036" alt="Screenshot 2024-04-11 at 5 44 17 PM" src="https://github.com/zenstackhq/zenstack/assets/25591626/fac14ab7-860f-4e93-9311-ab60875f9074">

**Environment (please complete the following information):**

-   ZenStack version: 2.0.0-beta.10
-   Prisma version: 5.9.1
-   Database type: Postgresql

**Comment by ymc9** [comment]
Thanks for reporting this @acdifran ! Will make a fix soon.

**Comment by ymc9** [comment]
Fixed in 2.0.0-beta.13

**Comment by eqqe** [comment]
Hello, I have a case where the index is declared in an abstract model, and it does not work.
