### ISSUE TITLE
Typecasting "Bytes" Fields

### ISSUE THREAD

**Issue by andrewpeters9** [zenstackhq/zenstack#1268]
**Description:**
- the `zod` plugin will create a validator like so for `Bytes` fields:   `z.union([z.string(), z.instanceof(Uint8Array)])` - i.e., a zod validator that infers to `Uint8Array`
- this is problematic as the schemas are then type-casted to a type that treats `Bytes` as a `Buffer` - see https://github.com/zenstackhq/zenstack/blob/2ce8b9bd2e9b963f48669ca7a52181a673e4c33c/packages/schema/src/plugins/zod/transformer.ts#L279
- this then results in a type-error (see screenshot)

**Solution:**
- Quick fix: 
  - Remove `:SchemaType` from the line above
  - Change `as SchemaType` to `as unknown as SchemaType`
- Elegant fix:
  - General background: 
    - Buffers aren't supported on the frontend, and have to be serialized + deserialized into a Uint8Array or another byte array
    - `Bytes` fields  are initially returned as a `Buffer` when directly interacting with the prisma client
    - Therefore, both types technically have some merit
  - A clean solution might be something like `z.custom<Buffer | Uint8Array>(data => data instanceof Uint8Array)`
    - NOTE: I haven't tested the above, but I believe it should work
    - The above would let us preserve those types, while not having to have a runtime Buffer object on the frontend

**Screenshots**
![image](https://github.com/zenstackhq/zenstack/assets/36251325/28070d27-77c1-425a-adf4-5d19ef288adc)

**Environment (please complete the following information):**

-   ZenStack version: [e.g., 2.0.0-beta.13]
-   Prisma version: [e.g., 5.12.1]
-   Database type: [e.g. MySQL]

**Comment by ymc9** [comment]
Thanks for filing this issue @andrewpeters9 ! I think `z.custom` is a great solution!

Please let me know if you have time to make a PR and I'll happy to facilitate. Otherwise I'll try making a fix during the weekend.

**Comment by ymc9** [comment]
Fixed in v2.0.0.
