### ISSUE TITLE
[Feature Request] Disable hooks that generates files outside of node_modules in CLI

### ISSUE THREAD

**Issue by Arkanii** [zenstackhq/zenstack#1379]
**Is your feature request related to a problem? Please describe.**

In my docker image build pipeline, I need to run `zenstack generate` to generate zenstack files (enhance, etc).
But I use the `@zenstackhq/tanstack-query` hook and this one override files I've already pushed in my repo.

**Describe the solution you'd like**

An option in the `zenstack generate` command to disable hooks that generates files outside of `node_modules`.
I'll gain in stability and build time.

Thanks !

**Comment by ymc9** [comment]
Got it. Yes, that makes very good sense. I think we can add a new switch "--plugin [name]" to the CLI (which can be provided multiple times) to explicitly specify what plugins to run. Similar to prisma CLI's "--generator" option.

Does this sound good to you? @Arkanii

**Comment by Arkanii** [comment]
Seems good to me !

**Comment by Arkanii** [comment]
Thanks for the functionality! I close the issue 😁
