### ISSUE TITLE
[BUG] Enum with "DateTime" Value

### ISSUE THREAD

**Issue by francistogram** [zenstackhq/zenstack#1399]
I have an enum with values from [Webflow's API](https://developers.webflow.com/data/reference/field-types-item-values#field-types) with all of the possible types
```typescript
enum WebflowFieldType {
  Image
  RichText
  Link
  Switch
  Reference
  PlainText
  VideoLink
  MultiImage
  Email
  Phone
  Number
  Option
  Color
  DateTime // Error is here
  File
  MultiReference
}
```

this worked in `prisma.schema` but with `schema.zmodel` I get this error
```
schema.zmodel:2344:3 - Expecting token of type '}' but found `DateTime`.
```

<img width="486" alt="image" src="https://github.com/zenstackhq/zenstack/assets/3721449/a6e2454f-03d1-46ff-8225-bdcf7d3c6067">

Seems like a bug cause there's no reason I shouldn't be able to have an enum named "DateTime" and it works in Prisma directly

**Comment by ymc9** [comment]
Fixed in 2.1.0

**Comment by francistogram** [comment]
Hey @ymc9 seems like I'm still running into the same issue on `v2.1.1`

<img width="571" alt="image" src="https://github.com/zenstackhq/zenstack/assets/3721449/b9b1abc0-740e-4a60-bd22-6a47cc6772c5">

<img width="163" alt="image" src="https://github.com/zenstackhq/zenstack/assets/3721449/d34a353e-421c-4f79-b65a-9df35293e0a3">

Looking at the test in the commit seems like it only tests for the name used as a field on a model vs an enum value that either
1. I'm doing something wrong (very possible)
2. The change fixed it for fields but not enum names

https://github.com/zenstackhq/zenstack/pull/1424/files#diff-7883ee0ee292eabaa7686a78d64d6af8bab02fcc845bb7352c3c4aee213c9512R19

**Comment by ymc9** [comment]
Oh, my apologies. You're right, the support was only added for model fields not enum fields ... Will make one more fix later today. Please also let me know if you're interested in making a PR 😄  @francistogram

**Comment by francistogram** [comment]
Happy to make a PR if ya don't mind pointing me on where to get started!

**Comment by ymc9** [comment]
> Happy to make a PR if ya don't mind pointing me on where to get started!

Awesome! You can make a fork and create a PR based off the "dev" branch.

I believe the only change needed is this line here: https://github.com/zenstackhq/zenstack/blob/fea8ec71eac83e880112d64057355e8d2979bd18/packages/language/src/zmodel.langium#L212C10-L212C19

`name=RegularID` to `name=RegularIDWithTypeName`.

If you run `pnpm build`, a few other files (like `ast.ts`) will be auto-updated and should be included in the change.

If you want to test it out locally, you can `pnpm build` in the `language` package, and copy over the content of "dist" folder into your node_modules.

Let me know if you run into any hurdle.

**Comment by francistogram** [comment]
I've made the change and was able to build it'

<img width="539" alt="image" src="https://github.com/zenstackhq/zenstack/assets/3721449/57f58f51-6752-4070-863e-6be315832b2a">

I am a little stuck with testing it locally

> If you want to test it out locally, you can pnpm build in the language package, and copy over the content of "dist" folder into your node_modules.

Was initially thinking maybe I'd copy over the changed files e.g. `ast.ts` but that file doesn't seem to exist in the `node_modules`, closest thing I found was `ast-utils.js`

Any pointers here on what I might be missing?

<img width="260" alt="image" src="https://github.com/zenstackhq/zenstack/assets/3721449/2e952fc8-841b-4bed-9cce-51c97d5f1a9c">

**Comment by ymc9** [comment]
Good to know the progress @francistogram ! The npm package corresponding to the "language" package is actually "@zenstackhq/language". You should be able to find "ast.js" at "node_modules/@zenstackhq/language".

**Comment by francistogram** [comment]
Ah the `@` explains why I hadn't seen it in the folder 🤦‍♂️ 

Almost there I think, unclear to me if this is an issue related with my change or with my `schema.zmodel` as this is my first time setting up zenstack (this issue was preventing me from migrating easily)

<img width="564" alt="image" src="https://github.com/zenstackhq/zenstack/assets/3721449/f61109ba-14c7-4035-a2e0-25d78cee0265">

These are some of the lines it's complaining about it you see any issues here?

<img width="477" alt="image" src="https://github.com/zenstackhq/zenstack/assets/3721449/3cf8b00a-53cd-45e7-a815-185d2ba2da99">

I went ahead and put up a PR in case this helps in debugging if I did anything wrong

 https://github.com/zenstackhq/zenstack/pull/1457

Thanks for the help here too!

**Comment by ymc9** [comment]
> Ah the `@` explains why I hadn't seen it in the folder 🤦‍♂️
> 
> Almost there I think, unclear to me if this is an issue related with my change or with my `schema.zmodel` as this is my first time setting up zenstack (this issue was preventing me from migrating easily)
> 
> <img alt="image" width="564" src="https://private-user-images.githubusercontent.com/3721449/331804620-f61109ba-14c7-4035-a2e0-25d78cee0265.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNjgxMjAsIm5iZiI6MTcxNjE2NzgyMCwicGF0aCI6Ii8zNzIxNDQ5LzMzMTgwNDYyMC1mNjExMDliYS0xNGM3LTQwMzUtYTJlMC0yNWQ3OGNlZTAyNjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjBUMDExNzAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjdkN2U4YWFlYmQyNjA5YWU2MTJkMjRhOGYwMmNiMTYxZTYyNjI4MDNlODU4NzYyMTYwNTFmZmZmNDkzMjFjMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.oG_0uGKREScnXwwU_8ysooZIPaOjED4BUkBg7PRaZMw">
> These are some of the lines it's complaining about it you see any issues here?
> 
> <img alt="image" width="477" src="https://private-user-images.githubusercontent.com/3721449/331804703-3cf8b00a-53cd-45e7-a815-185d2ba2da99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNjgxMjAsIm5iZiI6MTcxNjE2NzgyMCwicGF0aCI6Ii8zNzIxNDQ5LzMzMTgwNDcwMy0zY2Y4YjAwYS01M2NkLTQ1ZTctYTgxNS0xODVkMmJhMmRhOTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjBUMDExNzAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDc4NzE2YTVmMjFjYzM5YzJmYjFhMjlkZTlkYjZkMjcyMjg2ZWVkMGQyOTI2OWQxZWIwNDliMjI2Y2IxNjE1MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4H4558AKdHuSuDe20jmON0inO73C_q8VDjWr_sXg45o">
> I went ahead and put up a PR in case this helps in debugging if I did anything wrong
> 
> #1457
> 
> Thanks for the help here too!

Hey @francistogram , the change looks cool to me. I've merged it. And then I found I overlooked that reference expressions also need to respect reserved type names, otherwise enum fields cannot be properly resolved. I've pushed an extra fix.

Will publish a patch release today. Thank you for the work!

**Comment by ymc9** [comment]
The change is live in v2.1.2 now!
