### ISSUE TITLE
'unsetMarker' resolves to a type-only declaration and must be imported using a type-only import

### ISSUE THREAD

**Issue by NatoBoram** [zenstackhq/zenstack#1405]
**Description and expected behavior**
A clear and concise description of what the bug is and what's the expected behavior.

When using the TRPC plugin, it generates a file at `routers/index.ts` with this line:

```ts
import {
	unsetMarker,
	type AnyRootConfig,
	type CreateRouterInner,
	type ProcedureBuilder,
	type ProcedureParams,
	type ProcedureRouterRecord,
} from "@trpc/server"
```

This is associated with an error message:

> 'unsetMarker' resolves to a type-only declaration and must be imported using a type-only import when 'verbatimModuleSyntax' is enabled.

To fix this, we can write it like this:

```ts
import type {
	AnyRootConfig,
	CreateRouterInner,
	ProcedureBuilder,
	ProcedureParams,
	ProcedureRouterRecord,
	unsetMarker,
} from "@trpc/server"
```

**Screenshots**

![image](https://github.com/zenstackhq/zenstack/assets/10495562/f9ee3aa4-14c4-4ff1-b9a7-dfc1849f779f)

**Environment (please complete the following information):**

-   ZenStack version: "2.0.2"
-   Prisma version: "5.13.0"
-   Database type: Postgresql

**Additional context**

In the next version of trpc, these types are going to be moved/removed into a "unstable do not import" folder

**Comment by ymc9** [comment]
Hi @NatoBoram , I agree it should better be fixed. Just curious the file is generated to contain a "/* eslint-disable */" marker. Is your linter somehow configured to ignore it?

**Comment by NatoBoram** [comment]
This is a TypeScript error. I'm using strict TypeScript with all the strict options enabled.

It looks a bit like that:

https://github.com/NatoBoram/gigachad.ts/blob/cf95e1bfff14e3df9cf567a32d96c0fd86470cf9/tsconfig.json#L36-L59

**Comment by ymc9** [comment]
I see. Thanks for the clarification. Will make a fix soon. Please let me know if you're interested in making a PR and I'll be happy to facilitate 😄.

**Comment by NatoBoram** [comment]
Thanks!
