### ISSUE TITLE
[Doc] Update Clerk guide to Next.js app router

### ISSUE THREAD

**Issue by ymc9** [zenstackhq/zenstack#1419]
https://zenstack.dev/docs/guides/authentication/clerk

**Comment by andrictham** [comment]
@ymc9 I managed to get Clerk working with ZenStack and App Router

Here's what my code looks like in `/src/app/api/model/[...path]/route.ts`: https://gist.github.com/andrictham/1f4d729f33a63ab1fa817b40418f6e35

**Comment by ymc9** [comment]
It's live here now: https://zenstack.dev/docs/guides/authentication/clerk#create-an-enhanced-prisma-client

The sample project also has two branches for the app router and pages router, respectively.

@andrictham

**Comment by ymc9** [comment]
Fixed in v2.2.0
