### ISSUE TITLE
[Feature Request] Compatibility with Prisma 5.14 `createManyAndReturn`

### ISSUE THREAD

**Issue by ymc9** [zenstackhq/zenstack#1461]
https://github.com/prisma/prisma/releases/tag/5.14.0

**Comment by iamfj** [comment]
@ymc9 is there an estimation for the v2.2.0 release?

**Comment by ymc9** [comment]
I'm hoping before 6/15. Are you waiting to use `createManyAndReturn` thing 😄?

**Comment by ymc9** [comment]
Fixed in v2.2.0
