### ISSUE TITLE
[Feature Request] Allow Disabling of Version Check

### ISSUE THREAD

**Issue by tylergets** [zenstackhq/zenstack#1464]
**Is your feature request related to a problem? Please describe.**
The CLI currently uses  'get-latest-version' package to check for updates. In internet limited enviroments this causes zenstack generate to fail. It also adds unnecessary telemetary. 

**Describe the solution you'd like**
Allow disabling of the update check. 

**Describe alternatives you've considered**
If the update check fails, it could not cause the process to exit with non zero code.

**Additional context**
This is particulary import for building Zenstack projects using Nix. Partially related is #1046 

Thank you!

**Comment by ymc9** [comment]
Hi @tylergets ,

There's already a "--no-version-check" switch for "generate" and "init". Could you try if it works?

**Comment by ymc9** [comment]
V2.3.0 now has a 1000ms timeout fo the check.
