### ISSUE TITLE
Prisma schema validation error - Relation map argument is too long

### ISSUE THREAD

**Issue by ruizehung** [zenstackhq/zenstack#1466]
**Description and expected behavior**
When I use polymorphic feature withs models that have long names, I got Prisma schema validation error due to long `map` argument in `@relation` constraint. The maximum allowed length is 63 bytes for PostgreSql. The issue can be temporarily fixed by manually replacing the generated map argument with a shorter string.

I can see myself easily getting this error as I have descriptive model names.

**Screenshots**
![image](https://github.com/zenstackhq/zenstack/assets/35753861/2c171eae-6871-4bdf-a6a7-386a1bbbd752)

**Environment (please complete the following information):**

-   ZenStack version: 2.1.2
-   Prisma version: 5.13.0
-   Database type: Postgresql

**Additional context**
N/A

**Comment by ymc9** [comment]
Fixed in v2.2.0
