### ISSUE TITLE
Tanstack Svelte Query does not infer return type

### ISSUE THREAD

**Issue by bbozzay** [zenstackhq/zenstack#1488]
**Description and expected behavior**
Tanstack Svelte Query returns CreateQueryResult<unknown, Error> or any instead of inferring the correct return type.

**Environment (please complete the following information):**

-   ZenStack version: 2.1.2
-   Prisma version: 5.0.0 (and latest)
-   Database type: Postgresql

**Comment by ymc9** [comment]
Fixed in v2.2.0
