### ISSUE TITLE
[Feature Request] Create throws RESULT_NOT_READABLE when MySQL transaction_isolation is not "READ-UNCOMMITTED"

### ISSUE THREAD

**Issue by OiAnthony** [zenstackhq/zenstack#1523]
**Is your feature request related to a problem? Please describe.**
Create throws RESULT_NOT_READABLE when MySQL transaction_isolation is not "READ-UNCOMMITTED"

**Describe the solution you'd like**
1. Check MySQL transaction_isolation, when transaction_isolation is not equal to "Read-Uncommitted", LOG warning
2. Create and readBack Shouldn't it appear in the same thing? Dirty reading may appear

**Describe alternatives you've considered**
At present, I took the initiative to change MySQL transaction_isolation to "Read-Uncommitted"

**Additional context**
![image](https://github.com/zenstackhq/zenstack/assets/62509433/604237a5-31d5-4f90-82e9-0323239eaf1f)

**Comment by ymc9** [comment]
Hi @OiAnthony , thanks for reporting this. Yes, ZenStack relies on reading uncommitted changes to enforce access policies. For the specific case of checking readability after creating, we can do the read after committing the create, but there're other cases where reading uncommitted changes is needed. I'll see if we can detect the current transaction settings, and will at least add something to the documentation about it.

**Comment by ymc9** [comment]
Added to [limitations](https://zenstack.dev/docs/reference/limitations#minimum-transaction-isolation-level)
