### ISSUE TITLE
`@deny('read')` Field Policy - Not Reading Data

### ISSUE THREAD

**Issue by milimyname** [zenstackhq/zenstack#1528]
**Description and expected behavior**
Thank u for the great library. After #1452 which was solved in @2.1.1 but now members cannot get any data. 

`job @deny("read, update", space.memberships?[auth() == user && !(role in [owner, admin, roleManager])])`

**Environment (please complete the following information):**

-   ZenStack version: 2.2 and 2.1
-   Prisma version: 5.15
-   Database type: Postgresql

**Comment by ymc9** [comment]
Hi @milimyname , an unintended breaking change was fixed in release 2.2.3. Could you upgrade and give it a try?
