### ISSUE TITLE
Plugin Open API: Wrong Open API spec generated for `meta` response data key

### ISSUE THREAD

**Issue by drichardcarl** [zenstackhq/zenstack#1549]
**Description and expected behavior**
The plugin should generate the proper spec for `meta` response data key.

Currently, I'm using `npx openapi-typescript prisma/schema.json -o prisma/schema.d.ts` to auto generate typings from Open API spec which will be later used to create API client using `openapi-fetch`. The problem is that "meta" key in response data has a wrong spec to begin with, hence the generated type is also wrong.

The expected type is:
```ts
ResponseData = {
  ...,
  meta?: {...}
}
```
and not
```ts
ResponseData = {
  ...,
  meta?: {
    meta?: {}
  }
}
```

**Screenshots**
(schema.zmodel)
![image](https://github.com/zenstackhq/zenstack/assets/31929158/e91d7768-d475-47e7-9cec-89f8e6159b04)

(_Meta section of schema.json)
![image](https://github.com/zenstackhq/zenstack/assets/31929158/753de757-87aa-4bd2-9a89-e4846f0cb0c1)

(_Meta section of schema.d.ts)
![image](https://github.com/zenstackhq/zenstack/assets/31929158/7e599e4d-1757-4fa4-9eac-90455760798a)

(response from api call)
![image](https://github.com/zenstackhq/zenstack/assets/31929158/892cb216-2709-49d0-8f5b-6c2073c7c611)

**Environment (please complete the following information):**

-   ZenStack version: 2.2.4
-   Prisma version: 5.13.0
-   Database type: MySQL 8

**Additional context**
None

**Comment by ymc9** [comment]
Fixed in 2.5.0
