### ISSUE TITLE
Access policy failure on referenced object properties with overridden policies.

### ISSUE THREAD

**Issue by chunkerchunker** [zenstackhq/zenstack#1574]
**Description and expected behavior**

When a model declares a property with a property-level access policy that overrides the model policy, the property policy isn't used consistently.
* When the property is accessed directly, the property-level policy is respected.
* When the property is accessed via an *optional* relation, the property policy is respected.
* But when the property is accessed via a non-optional relation, the model policy takes precedence.

The last bullet is surprising and inconsistent in terms of protecting access, though I can see how it makes some sense.

Attached is a detailed test case showing the expected results.  All the checks in test succeed, except for the last.

[property-policy-relations.test.ts.txt](https://github.com/user-attachments/files/16184063/property-policy-relations.test.ts.txt)

**Environment (please complete the following information):**

-   ZenStack version: 2.2.4
-   Prisma version: 5.13 & 5.16.1 (shouldn't matter)
-   Database type: Postgresql & sqlite (shouldn't matter)

**Comment by ymc9** [comment]
Fixed in release 2.3.2
