### ISSUE TITLE
[Feature Request] Implement the Zmodel `Check` feature into the api check feature 

### ISSUE THREAD

**Issue by jasonmacdonald** [zenstackhq/zenstack#1612]
[*From Discord discussion*]
(https://discord.com/channels/1035538056146595961/1159194942787293255/1265774955518230579)

Currently, the `enhance.model.check` feature in preview does not support the `check(parent)` policy in the schema. If you use `check` in your model policy, it currently results in `Model$checker$create` containing an "empty" policy `{ kind: 'variable', name: '__var0', type: 'boolean' };`, whereas the `$check_Model_create` policy properly delegates to the parent. This feature request is to ensure the consistent functioning of the feature with other policy features.licy it currently results in `Model$checker$create` containing an "empty" policy  `{ kind: 'variable', name: '__var0', type: 'boolean' };` whereas the `$check_Model_create` policy properly delegates to the parent. This feature request is to make the feature work consistently with the other policy features

**Comment by ymc9** [comment]
Fixed in 2.8.0
