### ISSUE TITLE
@zenstackhq/trpc breaks with TypeScript error.

### ISSUE THREAD

**Issue by kirankunigiri** [zenstackhq/zenstack#1615]
**Description and expected behavior**
The `@zenstackhq/trpc` that adds a trpc router for Prisma with ZenStack seems to break due to this TypeScript error:
`The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed.ts(7056)`

Although the code still runs without transpilation, it causes issues with type completion in the IDE and makes type completions slow or completely breaks them and makes types show up as `any`. It looks like the types or too complex for it to handle. I've never seen an issue like this before though so I'm not sure how this could be fixed. I only have a few tables in my schema, so the types shouldn't be too complex.

**Environment (please complete the following information):**

-   ZenStack version: 2.3.3 (also using the same version for @zenstackhq/trpc)
-   Prisma version: 5.17.0
-   Database type: Postgresql

**Comment by ymc9** [comment]
Hi @kirankunigiri , this probably only happens with certain kinds of models. Do you have a sharable project?

**Comment by ymc9** [comment]
Btw what's your trpc version?

**Comment by kirankunigiri** [comment]
Hi, sorry for the late reply! I forgot I had opened this issue. After finding out that the trpc hooks didn't have optimistic updates, I actually ended up removing the trpc plugin and went with the zenstack fastify server adapter with react-query hooks instead. I wanted to mention that the react query hooks are really amazing and make development so much easier! The built-in optimistic updates feature is a huge game changer. Thanks to the zenstack team for making this. 

I would definitely recommend anyone else to also use the react query hooks instead. In my current project, I use a mix between trpc and zenstack hooks - the zenstack hooks are for calling prisma functions, and I added the fastify trpc plugin for anything else (custom backend endpoints).

Unfortunately I didn't save the old version of my project with the trpc hooks anywhere, so I can't replicate the issue. You can go ahead and close the issue, or we can keep it open in case someone else gets the same problem and can share their project info here.

**Comment by ymc9** [comment]
Thank you for the update @kirankunigiri and my apologies for the late reply 😄

I'm closing this issue for now.
