### ISSUE TITLE
Unauthenticated users can read from tables

### ISSUE THREAD

**Issue by Adhil523** [zenstackhq/zenstack#1627]
**Description and expected behavior**

Given the below schema, running  `db.gymUser.findMany()` without authentication in the repl returns all the user data.
```prisma
model Gym extends Base {
  // ...
  members            GymUser[]

  @@allow('all', auth().admin.role == "ADMIN")
  @@allow('create,read', auth() != null)
  @@allow('update', members?[user == auth() && role == "ADMIN"])
}

model GymUser extends Base {
  userID                 String
  user                   User             @relation(fields: [userID], references: [id])
  gymID                  String?
  gym                    Gym?             @relation(fields: [gymID], references: [id])
  role                   Role

  @@allow('create', auth() != null)
  @@allow('read',gym.members?[user == auth() && (role == "ADMIN" || role == "TRAINER")])
  @@allow('read,update', user == auth())
  @@allow('update', gym.members?[user == auth() && role == "ADMIN"])
  @@deny('update', future().userID != userID)

  @@unique([userID, gymID])

}
```

**Prisma Queries**

<details>
<summary>Query as anonymous user</summary>

```json
{
  "where": {
    "OR": [
      {
        "OR": [
          {
            "gym": {
              "members": {
                "some": {
                  "AND": [
                    {
                      "OR": []
                    },
                    {
                      "OR": [
                        {
                          "role": {
                            "equals": "ADMIN"
                          }
                        },
                        {
                          "role": {
                            "equals": "TRAINER"
                          }
                        }
                      ]
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    ]
  }
}
```

</details>
<details>
<summary>Query as an authenticated user</summary>

```json
{
  "where": {
    "OR": [
      {
        "OR": [
          {
            "gym": {
              "members": {
                "some": {
                  "AND": [
                    {
                      "user": {
                        "is": {
                          "id": "clymmldqa0000cd0svaueud8d"
                        }
                      }
                    },
                    {
                      "OR": [
                        {
                          "role": {
                            "equals": "ADMIN"
                          }
                        },
                        {
                          "role": {
                            "equals": "TRAINER"
                          }
                        }
                      ]
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    ]
  }
}
```

</details>

It seems like this part is the problem when `auth()` is null in this `@@allow('read',gym.members?[user == auth() && (role == "ADMIN" || role == "TRAINER")])`
```json
           "gym": {
              "members": {
                "some": {
                  "AND": [
                    {
                      "OR": []
                    },
```

Expected behavior is that `user==auth()` part will fail, as the query was based on the example provided in [the docs](https://zenstack.dev/docs/the-complete-guide/part1/access-policy/relations#%EF%B8%8F-adding-relation-based-access-control).

**Environment (please complete the following information):**

-   ZenStack version: 2.0.1
-   Prisma version: 5.12.1

**Additional context**
Might be related to #397

**Comment by sidharthv96** [comment]
Although the [reference doc](https://zenstack.dev/docs/reference/zmodel-language#a-more-complex-example-with-multi-user-spaces) mentions a check to require login, it's not obvious how big of an issue not having it is. 

```prisma
    // require login
    @@deny('all', auth() == null)
```

From my mental model, this policy is used to check the role of the current user. So that check should never pass if the user is undefined, as `user == auth()` will never match because user is not an optional field. 

```prisma
  // space admin can update and delete
  @@allow('update,delete', members?[user == auth() && role == 'ADMIN'])
```

But the policy seems to behave in a `fail-open` mode, which is not what we expect from a security perspective. 

For now, the fix is to add `@@deny('all', auth() == null)` to the Base model. But this is a pretty big foot gun for teams who might not know about this.

**Comment by ymc9** [comment]
Thanks for reporting and commenting @Adhil523 @sidharthv96 .

I still need to confirm, but I tend to believe this is related to this Prisma issue I reported quite a while ago:

**Comment by sidharthv96** [comment]
This seems like a prisma issue then. What are your thoughts on zenstack optimising queries? Is it out of scope?

```json
{"where":{"OR":[{"OR":[{"gym":{"members":{"some":{"AND":[{"OR":[]},{"OR":[{"role":{"equals":"ADMIN"}},{"role":{"equals":"TRAINER"}}]}]}}}}]}]}}
{"where":{"OR":[{"OR":[{"gym":{"members":{"some":{"AND":[false,{"OR":[{"role":{"equals":"ADMIN"}},{"role":{"equals":"TRAINER"}}]}]}}}}]}]}}
{"where":{"OR":[{"OR":[{"gym":{"members":{"some":false}}}]}]}}
{"where":{"OR":[{"OR":[false]}]}}
{"where":false}
return [] or throw;
```

**Comment by ymc9** [comment]
> This seems like a prisma issue then. What are your thoughts on zenstack optimising queries? Is it out of scope?
> 
> ```json
> {"where":{"OR":[{"OR":[{"gym":{"members":{"some":{"AND":[{"OR":[]},{"OR":[{"role":{"equals":"ADMIN"}},{"role":{"equals":"TRAINER"}}]}]}}}}]}]}}
> {"where":{"OR":[{"OR":[{"gym":{"members":{"some":{"AND":[false,{"OR":[{"role":{"equals":"ADMIN"}},{"role":{"equals":"TRAINER"}}]}]}}}}]}]}}
> {"where":{"OR":[{"OR":[{"gym":{"members":{"some":false}}}]}]}}
> {"where":{"OR":[{"OR":[false]}]}}
> {"where":false}
> return [] or throw;
> ```

Yes, I agree reduction is the way to go. And it's more than an optimization, but rather for correctness ... Will add it soon.
