### ISSUE TITLE
Cannot find module './zod' or its corresponding type declarations.

### ISSUE THREAD

**Issue by Tsimopak** [zenstackhq/zenstack#1667]
An error in line 6 of the generated enhance.ts 

This happens when I provide the enhancer plugin in schema.zmodel like so, 
![image](https://github.com/user-attachments/assets/1ecf0334-4b9e-4857-ab5f-836ab34cd63f)

This happens when I provide the enhancer plugin in schema.zmodel like so, 
![image](https://github.com/user-attachments/assets/3694bd57-8e66-4923-b31b-742a33328219)

Why do I provide it again with the default settings? Because apparently, Zenstack does not generate the enhance API in node_modules/.zenstack if I don't
However, if I do provide the plugin, the CLI complains about the aforementioned error when I do zenstack generate
![image](https://github.com/user-attachments/assets/e957f11c-76b6-4923-a9b4-a1980a691a6a)

* ZenStack CLI v2.4.1
* zenstack@2.4.1
* prisma@5.18.0
* Postgress

Reference from discord: https://discord.com/channels/1035538056146595961/1274540789946388551/1274540789946388551

**Comment by jiashengguo** [comment]
@ymc9  should we change the generated import path for zod?
```ts
import * as zodSchemas from '@zenstackhq/runtime/zod'
```

**Comment by ymc9** [comment]
> @ymc9 should we change the generated import path for zod?
> 
> ```ts
> import * as zodSchemas from '@zenstackhq/runtime/zod'
> ```

I roughly remember we couldn't do that due to cyclic references. Let me check why it's broken.

**Comment by zysam** [comment]
@ymc9 could you release  version like beta or others on npm?  so I can run the script.

**Comment by spacesick** [comment]
Here is my workaround in the meantime: Add the following to `schema.zmodel`,
![image](https://github.com/user-attachments/assets/8173cc5c-4128-4123-ae46-82ac7f967a94)
and import what you need from `"./generated_zenstack/<module name>"`

**Comment by ymc9** [comment]
Fixed in 2.5.0
