### ISSUE TITLE
default of auth().id to createdBy in createManyAndReturn API doesn't work

### ISSUE THREAD

**Issue by danielpaz6** [zenstackhq/zenstack#1681]
I'm trying to use `createManyAndReturn` API on polymorphic model, the base of the model (not the polymorphic part) has `createdBy` field, but when I'm trying to use it, I get the following error: 

  'Argument `createdBy` is missing.'

```
createdById Int @default(auth().id)
createdBy User @relation('ShelfCreatedBy', fields: [createdById], references: [id]) 
```

zenstack: 2.4.1
prisma: 5.18.0

**Comment by ymc9** [comment]
Fixed in 2.6.0
