### ISSUE TITLE
Pass computed properties to Zenstack Query Hooks in Vue

### ISSUE THREAD

**Issue by 0x15F9** [zenstackhq/zenstack#1683]
I have configured zenstack for nuxt js and I am using the tanstack-query plugin. I would like to fetch data using `useFindMany{}` and in the where clause set the value based from a ref or computed property. How should I proceed?

**Comment by genu** [comment]
The way you should do it is to make the whole first argument a computed property.

**Comment by ymc9** [comment]
@0x15F9 please see comments from @genu . Closing for now.

**Comment by 0x15F9** [comment]
An example would be helpful

**Comment by genu** [comment]
You can do something like this: 

```ts
const { data } = useFindFirstPost(
    computed(() => ({ where: { id: id.value } }))
  )
```

**Comment by 0x15F9** [comment]
Thanks for the tip!

**Comment by 0x15F9** [comment]
Awesome, thank you so much!
