### ISSUE TITLE
[Feature Request] New scope shorthand syntax in @@allow and @@deny

### ISSUE THREAD

**Issue by LilaRest** [zenstackhq/zenstack#1711]
**Describe the solution you'd like**
To avoid repeating multiple time the condition of an access policy which is error-prone and harder to maintain, the `@@allow` and `@@deny` statements in ZModels could also accept an Array as first parameter.

Example:
```prisma
@@allow(["read", "update", "delete"], auth() == this)
```

Instead of: 
```prisma
@@allow("read", auth() == this)
@@allow("update", auth() == this)
@@allow("delete", auth() == this)
```

**Describe alternatives you've considered**
I've considered using something like that, but that's less explicit and so more error-prone:
```prisma
@@allow("all", auth() == this)
@@deny("create", true)
```

**Comment by LilaRest** [comment]
I just found in a random place in the docs that the valid syntax to achieve that is:
```prisma
@@allow("read,update,delete", auth() == this)
```

So no issue here, just require a bit more documentation about this syntax.

**Comment by ymc9** [comment]
It's currently mentioned in this part of reference: https://zenstack.dev/docs/reference/zmodel-language#model-level-policy and in the complete guide: https://zenstack.dev/docs/the-complete-guide/part1/access-policy/model-level

Closing for now and we'll continue watching for similar comments and see how to improve.
