### ISSUE TITLE
[Feature Request] Fix OpenAPI documentation generator crash for RPC endpoints

### ISSUE THREAD

**Issue by daaain** [zenstackhq/zenstack#1717]
**Is your feature request related to a problem? Please describe.**
Currently for RPC endpoints the OpenAPI plugin generates a massive JSON file (100K+ lines for ~20 models), which makes the browser stall when using Swagger UI and trying to expand an API definition (eventually a popup asks to stop the script) and crash Redocly CLI with `FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory`.

**Describe the solution you'd like**
A way to configure the depth the types that are generated by the OpenAPI plugin to put a limit on the size of each endpoint's schema.

**Describe alternatives you've considered**
I guess the documentation generators could also prevent this issue on their side.

**Additional context**
See [this Discord thread](https://discord.com/channels/1035538056146595961/1285207929364156416) for more context.

**Comment by matmill5** [comment]
@daaain experiencing the same issue! I was able to work with our openapi documentation generator vendor to improve the performance on their end, but it still isn't great... I think simply reducing the depth of the generated openapi spec would be sufficient.

**Comment by ymc9** [comment]
Fixed in 2.9.0

A new "omitInputDetails" plugin option is added to reduce the generated spec size.
