### ISSUE TITLE
@@unique on polymorphic models

### ISSUE THREAD

**Issue by SinPP** [zenstackhq/zenstack#1758]
**Description and expected behavior**
I am trying to use polymorphic models. I have a base model and a model which extends the base model. I want to create a unique constraint on the extended model which includes a combination of the base model and the extend model. It fails with an error telling me that the field is not found on the extended model.

**Screenshots**
![image](https://github.com/user-attachments/assets/ecdc860e-4319-4552-8959-556e489bfa9b)

**Environment (please complete the following information):**
-   ZenStack version: ^2.6.2
-   Prisma version: ^5.20.0
-   Database type: Postgresql

**Additional context**
Error: Error validating model "Store": The unique index definition refers to the unknown fields: organizationId.

```
model Content {
    contentType String

    organization   Organization @relation("OrganizationContents", fields: [organizationId], references: [id])
    organizationId String       @db.Uuid

    @@delegate(contentType)
}
```

```
model Store extends Content {
    name      String

    @@unique([organizationId, name])
}
```

**Comment by ymc9** [comment]
Hi @SinPP , thanks for filing this.

Unfortunately using fields from base model in unique constraint is not possible, because at Prisma level, the base and concrete models are distinct tables connected with a relation.

We can improve the checker to report an error for such usage.

**Comment by lzw1926** [comment]
Hi, @ymc9  just curious is there any workaround for this demand? either with zenstack or not.

**Comment by ymc9** [comment]
> Hi, @ymc9 just curious is there any workaround for this demand? either with zenstack or not.

Hi @lzw1926 , I think it's really an intrinsic coming from the multi-table-inheritance design. The delegate and concrete models are literally different tables and there's no direct way to define a unique constraint that works across tables.
