### ISSUE TITLE
Allow to specify zenstack generate output folder in repl CLI

### ISSUE THREAD

**Issue by platon-ivanov** [zenstackhq/zenstack#1768]
**Is your feature request related to a problem? Please describe.**

The repl command allows us to provide a `--prisma-client` option. However, when I do, I get:

```
An unexpected error occurred:
 Error: Generated "enhance" function not found. Please run `zenstack generate` first.
```

I did run `zenstack generate` from the root of the project and pointed to the `prisma generate` output folder. The problem is that I also have a custom `zenstack generate` output folder, so `repl` wouldn't detect it automatically.

**Describe the solution you'd like**
`--schema` option to specify a custom location to load ZenStack generated modules.

**Comment by ymc9** [comment]
Fixed in 2.8.0
