### ISSUE TITLE
policy errors with polymorphic models

### ISSUE THREAD

**Issue by j0rdanba1n** [zenstackhq/zenstack#1770]
My zmodels are:

```
abstract model BaseAuth {
    id             String        @id @default(uuid())
    dateCreated    DateTime      @default(now())
    dateUpdated    DateTime      @updatedAt @default(now())

    organizationId String?
    organization   Organization? @relation(fields: [organizationId], references: [id], name: "organization")

    @@allow('all', organization.users?[user == auth()])
}

enum ResourceType {
    Personnel
}

model Resource extends BaseAuth {
    name     String?
    type     ResourceType?
    costRate Int?

    budgets  ResourceBudget[]

    @@delegate(type)
}

model Personnel extends Resource {
}
```

I get this error when trying to query a resource:

```
Invalid `prisma.resource.findMany()` invocation:

{
  where: {
    OR: [
      {
        OR: [
          {
            organization: {
              users: {
                some: {
                  user: {
                    is: {
                      id: "553a6c87-3a77-475b-8f56-f5fb59f92630"
                    }
                  }
                }
              }
            }
          }
        ]
      }
    ]
  },
  include: {
    delegate_aux_personnel: {
      where: {
        OR: [
          {
            OR: [
              {
                organization: {
                  users: {
                    some: {
                      user: {
                        is: {
                          id: "553a6c87-3a77-475b-8f56-f5fb59f92630"
                        }
                      }
                    }
                  }
                }
              }
            ]
          }
        ]
      },
      include: {
        delegate_aux_resource: {}
      }
    }
  }
}

Unknown argument `organization`. Available options are marked with ?.
```

_Originally posted by @j0rdanba1n in https://github.com/zenstackhq/zenstack/issues/1734#issuecomment-2404568533_

**Comment by j0rdanba1n** [comment]
@ymc9 - happy to help fix this if it's a bug - I might just need some pointers

**Comment by ymc9** [comment]
Thanks for filing this @j0rdanba1n . Is this with the latest version? I'll check it and update back here.

**Comment by j0rdanba1n** [comment]
Yes - it is with latest version :)

**Comment by j0rdanba1n** [comment]
@ymc9 do you have any idea what the problem is? This is currently blocking me. Thank you :)

**Comment by ymc9** [comment]
> abstract model BaseAuth {
>     id             String        @id @default(uuid())
>     dateCreated    DateTime      @default(now())
>     dateUpdated    DateTime      @updatedAt @default(now())
> 
>     organizationId String?
>     organization   Organization? @relation(fields: [organizationId], references: [id], name: "organization")
> 
>     @@allow('all', organization.users?[user == auth()])
> }
> 
> enum ResourceType {
>     Personnel
> }
> 
> model Resource extends BaseAuth {
>     name     String?
>     type     ResourceType?
>     costRate Int?
> 
>     budgets  ResourceBudget[]
> 
>     @@delegate(type)
> }
> 
> model Personnel extends Resource {
> }

Hey, I can reproduce the issue now. Will try to make a fix in the upcoming v2.7 release.

**Comment by j0rdanba1n** [comment]
omg! thank you for such a quick fix <3 when do you expect to release v2.7.0?

**Comment by eqqe** [comment]
Hello, I also have a problem when adding an index on model Resource

@@index([organizationId])

Does not compile for prisma because it copies the index to the delegated model

**Comment by eqqe** [comment]
https://github.com/zenstackhq/zenstack/issues/1786
