### ISSUE TITLE
[Feature Request] Expose types from enhanced prisma client

### ISSUE THREAD

**Issue by cudba** [zenstackhq/zenstack#1803]
Prisma allows to access types for db operations in the form of 
```typescript 
type PostCreateBody = Prisma.Args<typeof prisma.post, 'create'>['data']
```
 When using the enhanced Prisma Client, those types do not match anymore (assume due to the access policies).  I get some errors regarding relationships.

It would be convenient if those new types were exposed. It seems they live under `node_modules/.zenstack/.logical-prisma-client/index-fixed.d.ts` but don't think they are exposed.

Maybe there is some good reason for it or they are exposed and I'm just not able to figure it out, then pardon.

Thanks for the great work, much appreciated

**Comment by ymc9** [comment]
Hi @cudba , it's actually reexported from `@zenstackhq/runtime/models`. Let me find a proper place to add it to the docs ...

**Comment by ymc9** [comment]
Finally, added here: https://zenstack.dev/docs/reference/enhanced-types
