### ISSUE TITLE
[Feature Request] Option to pass ZenStack attribute comments to the generated Prisma schema

### ISSUE THREAD

**Issue by trancong12102** [zenstackhq/zenstack#1844]
**Is your feature request related to a problem? Please describe.**
I have a Prisma generator that uses Zenstack attribute triple-slash comments for configuration. However, after upgrading to ZenStack 2.8.0, it no longer works because all ZenStack attribute comments are removed in the generated Prisma schema.

**Describe the solution you'd like**
An option to enable or disable passing attribute comments to the generated Prisma schema.

**Describe alternatives you've considered**

**Additional context**
I can submit a pull request to address this issue if this feature is accepted.

**Comment by ymc9** [comment]
Hi @trancong12102 , it's now controlled by an option (off by default). I forgot to add it to the docs. Doing it now 😄

```prisma
plugin prisma {
  provider = '@core/prisma'
  customAttributesAsComments = true
}
```

What do you use these docs for?

**Comment by trancong12102** [comment]
My generator read custom attribute comments from dmmf as generate options.
Thank you so much!
