### ISSUE TITLE
"Reference not resolved" error when using an `enum` from an imported schema in `@default`

### ISSUE THREAD

**Issue by genu** [zenstackhq/zenstack#1849]
**Description and expected behavior**
When importing an `enum` from an imported schema, an error is thrown when using the value as `defualt`

```ts
import "./includes/enum"

model Post {
  ...
  status     Status   @default(PUBLISHED) <---throws "Reference not resolved: Status" error
  ...
}
```

This, however, works:

```ts
import "./includes/enum"

model Post {
  ...
  status     Status     <-- No error thrown
  ...
}
```

**Environment (please complete the following information):**

-   ZenStack version: 2.8.1
-   Database type: postgres

**Additional context**

**Comment by ymc9** [comment]
Fixed in 2.9.0
