### ISSUE TITLE
Package @zenstackhq/tanstack-query is missing when building a Nuxt 3 app for production.

### ISSUE THREAD

**Issue by emadzz** [zenstackhq/zenstack#1867]
**Description and expected behavior**
When running `npm run build` to build a Nuxt 3 app, the command fails due to the following error:

```
Nuxt Build Error: [vite]: Rollup failed to resolve import "@zenstackhq/tanstack-query/runtime-v5" from "<...>/my-project/lib/hooks/index.ts".
```

**Screenshots**
N/A

**Environment (please complete the following information):**

-   ZenStack version: [e.g., 2.0.0]
-   ZenStack version: 2.8.1
-   Nuxt version: 3.14.159 (Vite)
-   Node / Package manager version:  v20.14.0 (npm: 10.7.0)
-   Prisma version: n/a
-   Database type: n/a

**Additional context**
In the documentation, the code snippet installs `@zenstackhq/tanstack-query` as a `devDependencies` which gets removed when running `npm run build` / `nuxt build`.

<img width="847" alt="Screenshot 2024-11-18 at 00 26 38" src="https://github.com/user-attachments/assets/43b26002-fc68-4a6c-b73b-9ce24704e3f7">

 **Moving the dependency to `dependencies` fixes this issue.**

I'm not familiar with building tools like Vite but it seems this is an intended behavior and maybe the documentation should be updated?

**Comment by ymc9** [comment]
Hi @emadzz , the doc is outdated. Please install "@zenstackhq/tanstack-query" without the "-D" flag. It needs to be a regular dependency instead of dev. I'll fix the doc. Thanks for reporting this!

**Comment by emadzz** [comment]
Hi @ymc9 , I see that documentation is fixed. Thank you!
