### ISSUE TITLE
[Feature Request] Allow Unsupported field types in @@index

### ISSUE THREAD

**Issue by cudba** [zenstackhq/zenstack#1870]
I'm working with the postgis extension and want to add an index to a geometry like this

```
model Polygon {
    ...
    geometry    Unsupported("geometry(MultiPolygon, 4326)")

    @@index([geometry], name: "parcel_polygon_idx", type: Gist)
}
```

This works in the regular prisma schema, but in the model.zschema I get the following error

` Field of "Unsupported" type cannot be used in expressions`

Now I have to add this @@index manually into the prisma file each time I generate it which is not ideal obviously.

**Comment by ymc9** [comment]
fixed in 2.10.0
