### ISSUE TITLE
[Feature Request] Support hook cancellation / abort

### ISSUE THREAD

**Issue by Tsimopak** [zenstackhq/zenstack#1872]
The idea is to be able to abort hook fetching when it's not relevant anymore, for example when toggling between pages - this is a crucial thing to cancel the previous fetch otherwise the data may be not correct.

Discord discuss: https://discord.com/channels/1035538056146595961/1307893921589760061/1307893921589760061

In case it is possible, I would add it to the documentation: https://zenstack.dev/docs/reference/plugins/tanstack-query

**Comment by ymc9** [comment]
fixed in 2.10.0
