### ISSUE TITLE
Warning during generate since 2.9.0: Could not resolve PrismaClient type declaration path. This may break plugins that depend on it.

### ISSUE THREAD

**Issue by marekryb** [zenstackhq/zenstack#1875]
**Description and expected behavior**
Since upgrading to version `2.9.0`, I am having a warning during `zenstack generate` command. 
```⌛ ZenStack CLI v2.9.0, running plugins
⠋ Generating Prisma schemaCould not resolve PrismaClient type declaration path. This may break plugins that depend on it.
✔ Generating Prisma schema
✔ Generating PrismaClient enhancer
```

This happens only in monorepo setup. I initially tried to reproduce in 'plain' repo, but could not.
It is probably related to the fact that I specify custom prisma output directory.

Repro repo: https://github.com/marekryb/zenstack-290-warning

**Environment (please complete the following information):**

-   ZenStack version: 2.9.0
-   Prisma version: 5.22.0
-   Database type: any (tried sqlite and postgres)

**Additional context**
I am using pnpm. Did not try with npm or yarn workspaces.

**Comment by ymc9** [comment]
Hi @marekryb , thanks for reporting this. I'll look into it.

**Comment by tony-cocco** [comment]
Came here after hitting this error and having just upgraded to `2.9.1`. Was still having the issue but was able to fix it by adding an `output` dir.

Before:
```
generator client {
  provider = "prisma-client-js"
}
```

After:
```
generator client {
  provider = "prisma-client-js"
  output = "./generated"
}
```

**Comment by ymc9** [comment]
> Came here after hitting this error and having just upgraded to `2.9.1`. Was still having the issue but was able to fix it by adding an `output` dir.
> 
> Before:
> 
> ```
> generator client {
>   provider = "prisma-client-js"
> }
> ```
> 
> After:
> 
> ```
> generator client {
>   provider = "prisma-client-js"
>   output = "./generated"
> }
> ```

Hi @tony-cocco , is it a pnpm monorepo?

**Comment by tony-cocco** [comment]
Hi @ymc9 - yes. I tried to compare with the sample repo in the original post but it's currently a 404 for me.

**Comment by ymc9** [comment]
> Hi @ymc9 - yes. I tried to compare with the sample repo in the original post but it's currently a 404 for me. Happy to provide any other config we are using.

Got it. I think I know what's going on. Will make a 2.9.2 fix.

**Comment by ymc9** [comment]
Hello guys, could you try if you still have the warning with the new 2.9.2 release?

**Comment by tony-cocco** [comment]
> Hello guys, could you try if you still have the warning with the new 2.9.2 release?

Change snippet:

```diff
   zenstack:
-    "@zenstackhq/runtime": 2.8.1
-    "@zenstackhq/tanstack-query": 2.8.1
-    "@zenstackhq/server": 2.8.1
-    zenstack: 2.8.1
+    "@zenstackhq/runtime": 2.9.2
+    "@zenstackhq/tanstack-query": 2.9.2
+    "@zenstackhq/server": 2.9.2
+    zenstack: 2.9.2
```

I was also interested in using the new `portable` flag for the `hooks` plugin and added that as well. 

I do NOT have the warning. My build also seems to be back to stable unlike the 2.9.1 version. I want to say 2.9.2 fixed everything for me. ❤️

**Comment by ymc9** [comment]
Thank you for the confirmation @tony-cocco !

**Comment by sourcebert** [comment]
I can also confirm that the warning is no longer displayed with the new version. Thank you so much for the quick fix! 🎉 

The only warning that remains is:

```shell
Failed to format Prisma schema file
```

However, this is probably a separate issue... 😅

**Comment by ymc9** [comment]
> I can also confirm that the warning is no longer displayed with the new version. Thank you so much for the quick fix! 🎉
> 
> The only warning that remains is:
> 
> ```shell
> Failed to format Prisma schema file
> ```
> 
> However, this is probably a separate issue... 😅

Yes, likely a separate issue ... do you have a sharable repro?

**Comment by ymc9** [comment]
I'm closing it for now since the original issue is resolved. Please help create separate issues as needed. Thanks!
