### ISSUE TITLE
Bug: npx zenstack@latest init is giving error becouse is installing prima 6

### ISSUE THREAD

**Issue by israelins85** [zenstackhq/zenstack#1905]
**Description and expected behavior**
npx zenstack@latest init is giving error becouse is installing prima 6 Installing package "zenstack@2.9.4" with npm

**Environment (please complete the following information):**
New project

**Additional context**
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: mantine-next-template@1.0.0
npm error Found: prisma@6.0.1
npm error node_modules/prisma
npm error   dev prisma@"^6.0.1" from the root project

**Comment by ymc9** [comment]
fixed in 2.10.0
