### ISSUE TITLE
[Bug] - triple-slash comments are not persisting to schema in logical-prisma-client 

### ISSUE THREAD

**Issue by FominSergiy** [zenstackhq/zenstack#1909]
**Description and expected behavior**

The customAttributesAsComments flag released in `v2.8.0` works for the output schema of `zenstack generate`, but does not affect the comments inside the schema generated in `.logical-prisma-client/schema.prisma`

I updated plugin section accordingly:

plugin prisma {
  provider = '@core/prisma'
  output = './prisma/schema.prisma'
  customAttributesAsComments = true
}

![Screenshot 2024-12-10 at 09 17 14](https://github.com/user-attachments/assets/fa8ff173-bbc1-4a32-b462-dbd7259fa3d4)

**Environment (please complete the following information):**

-   ZenStack version: `v2.10.0` but the bug found in a feature introduced in `v2.8.0`
-   Prisma version: `6.0.1`

**Additional context**

Discovered this as I was going through the upgrade of zenstack from `v2.5.1` to `v2.10.0`.

**Comment by ymc9** [comment]
Fixed in 2.10.1

**Comment by FominSergiy** [comment]
great, much much appreciated!
