### ISSUE TITLE
[Feature Request] enhance function's user parameter id, expected to be string | undefined

### ISSUE THREAD

**Issue by cqh963852** [zenstackhq/zenstack#1914]
**Is your feature request related to a problem? Please describe.**

While using zenstack with next-auth@5. ts show me `Type 'undefined' is not assignable to type 'string'.`

![image](https://github.com/user-attachments/assets/aa409db3-cfe6-4aee-bef5-3d1feefc42e0)

I think in some scenarios, such as user registration, there is no user id at this time.

**Describe the solution you'd like**

remove the required props;

![image](https://github.com/user-attachments/assets/7bdb0ac9-4386-4cab-bcdb-d9263978663d)

**Comment by ymc9** [comment]
Hi @cqh963852 , when the user id is not available, what's the expected authorization behavior that you desire? Usually people want to treat it as an anonymous user and if so, you can call `enhance` with `undefined` user object.

**Comment by cqh963852** [comment]
> Hi @cqh963852 , when the user id is not available, what's the expected authorization behavior that you desire? Usually people want to treat it as an anonymous user and if so, you can call `enhance` with `undefined` user object.

Thanks for your reply. When the user is anonymous, the User object may not exist (`undefined | null`).  

But currently if I pass a `undefined user` in the context parameter. ts will reports an error, undefined cannot be assigned to string.

```
let user: {id:string}|undefined

// this will give an ts error.
enhace(prisma,{user})
```

**Comment by ymc9** [comment]
This is unexpected because the `enhance` API should always allow `user` to be `undefined`.
<img width="796" alt="image" src="https://github.com/user-attachments/assets/b50be5f0-6865-48b8-9f2c-b292fe89497e" />

What version of ZenStack are you on? Do you have a sharable project?

**Comment by cqh963852** [comment]
> This is unexpected because the `enhance` API should always allow `user` to be `undefined`. <img alt="image" width="796" src="https://private-user-images.githubusercontent.com/104139426/397961674-b50be5f0-6865-48b8-9f2c-b292fe89497e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5MjE1NjQsIm5iZiI6MTczNDkyMTI2NCwicGF0aCI6Ii8xMDQxMzk0MjYvMzk3OTYxNjc0LWI1MGJlNWYwLTY4NjUtNDhiOC05ZjJjLWIyOTJmZTg5NDk3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QwMjM0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NTVlNjVlNDM3YTBjOTgxYjJjMWU3NDA0OTZhMzRiNGUyOTRhMGY3MTYyYTgyN2JmZDU1NzVhYjdlNWE2NzRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Re6rbBuoIX132e9mBCjl4B6LJXWyOMsLbY9xaIY4TtM">
> 
> What version of ZenStack are you on? Do you have a sharable project?

Sorry I got that wrong earlier.

The enhance can accept a undefined user.

but it requires user's id not be undefined.

The default user id of next-auth may be undefined.

I have also tried rewriting the interface. Since the interface follows the merge, there is no way to change id string | undefined to string

![image](https://github.com/user-attachments/assets/5c3c03cb-280d-45cb-b96b-459c337b3957)

**Comment by ymc9** [comment]
> > This is unexpected because the `enhance` API should always allow `user` to be `undefined`. <img alt="image" width="796" src="https://private-user-images.githubusercontent.com/104139426/397961674-b50be5f0-6865-48b8-9f2c-b292fe89497e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5MjE1NjQsIm5iZiI6MTczNDkyMTI2NCwicGF0aCI6Ii8xMDQxMzk0MjYvMzk3OTYxNjc0LWI1MGJlNWYwLTY4NjUtNDhiOC05ZjJjLWIyOTJmZTg5NDk3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QwMjM0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NTVlNjVlNDM3YTBjOTgxYjJjMWU3NDA0OTZhMzRiNGUyOTRhMGY3MTYyYTgyN2JmZDU1NzVhYjdlNWE2NzRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Re6rbBuoIX132e9mBCjl4B6LJXWyOMsLbY9xaIY4TtM">
> > What version of ZenStack are you on? Do you have a sharable project?
> 
> Sorry I got that wrong earlier.
> 
> The enhance can accept a undefined user.
> 
> but it requires user's id not be undefined.
> 
> The default user id of next-auth may be undefined.
> 
> I have also tried rewriting the interface. Since the interface follows the merge, there is no way to change id string | undefined to string
> 
> ![image](https://private-user-images.githubusercontent.com/17702287/398037507-5c3c03cb-280d-45cb-b96b-459c337b3957.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5MjI0ODcsIm5iZiI6MTczNDkyMjE4NywicGF0aCI6Ii8xNzcwMjI4Ny8zOTgwMzc1MDctNWMzYzAzY2ItMjgwZC00NWNiLWI5NmItNDU5YzMzN2IzOTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDAyNDk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmOWIyZDU2ZGQzODgzMDRiMWViNTM2ZmUzODY0NDJiZDc5NzQyMjIxMDJhOGUyYTRlYTViNDJjYjBhMGYwNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Eoq47IONkJ1LHTyauVWHc5LAfj1wGnc1s0ytPfjumlA)

Got it. The current design of zenstack requires when a user context is provided, it must have a non-nullish id. You'll need to detect the next-auth's case and turn the entire user object to undefined if the id is not available.
