### ISSUE TITLE
Multi-file support

### ISSUE THREAD

**Issue by keanugrieves** [zenstackhq/zenstack#263]
**Is your feature request related to a problem? Please describe.**
It can be hard to find models in a large `schema.zmodel`

**Describe the solution you'd like**
ZenStack already does a pretty radical overhaul of `schema.prisma`. If we could compose it using multiple `*.zmodel` files, that could be another QOL feature that Prisma doesn't support.

**Describe alternatives you've considered**
Libraries like [prismix](https://github.com/jamiepine/prismix) or [schemix](https://github.com/ridafkih/schemix).

**Comment by ymc9** [comment]
Thanks, @keanugrieves .  Yes, multi-file schema makes a lot of sense, especially for large models. @jiashengguo is already working on it 😄.

@jiashengguo maybe we can close #260 and continue the discussion here?

**Comment by ajmnz** [comment]
👋

If it is of any help, I built [prisma-import](https://github.com/ajmnz/prisma-import) a couple of months ago, which _I think_ is the only solution not compromising DX and other features. It has a dedicated vscode extension, language server and CLI.

Hope it helps!

**Comment by jiashengguo** [comment]
@ajmnz  Thanks for the building and sharing it. It would be a good reference for me to implement it in ZenStack.

**Comment by jiashengguo** [comment]
Fixed by #365
