### ISSUE TITLE
Improve CLI performance

### ISSUE THREAD

**Issue by ymc9** [zenstackhq/zenstack#266]

**Comment by AWash227** [comment]
In the past, when working on generators, I found that ts-morph adds a lot of overhead as opposed to just writing files. If ts-morph needs to initialize the typescript AST, then it hangs for a bit. Maybe something to look into.

**Comment by ymc9** [comment]
Thanks! I suspected ts-morph is the culprit too 😄. Maybe there are some features in it I can tweak.
