### ISSUE TITLE
VSCode extension marks @ignore and @@ignore as non existing

### ISSUE THREAD

**Issue by jonathangerbaud** [zenstackhq/zenstack#280]
I'm using the `@ignore` and `@@ignore` attribute in my `schema.zmodel` file, but oddly, the VSCode extension does not recognize them.

As such, they are underlined in red.

On the other end, I got no error when I use `npx zenstack generate`

**Comment by ymc9** [comment]
Hi @jonathangerbaud, thanks for reporting this! The VSCode plugin was one build behind the CLI. I've just updated a new version 1.0.17. Please upgrade and see if it works now.

**Comment by jonathangerbaud** [comment]
Yes, it's working now, no more errors :)
