### ISSUE TITLE
`@core/zod` and Prisma preview features

### ISSUE THREAD

**Issue by keanugrieves** [zenstackhq/zenstack#337]
**Description and expected behavior**
These are also unaddressed issues in the underlying libraries:

- https://github.com/omar-dulaimi/prisma-trpc-generator/issues/72
- https://github.com/omar-dulaimi/prisma-zod-generator/issues/57

**`fullTextSearch`**

![fullTextSearch](https://user-images.githubusercontent.com/51007475/230832338-f5592e33-9dfd-4a6f-87ec-f332e32c0a9d.png)

In the first screenshot, `Company.schema.ts` should import `CompanyOrderByWithRelationAndSearchRelevanceInputObjectSchema` from `./objects/CompanyOrderByWithRelationAndSearchRelevanceInput.schema`.

The error might stem from these lines: https://github.com/zenstackhq/zenstack/blob/19253ca3ddc34c748cb3271e13cd0d5d09f4c194/packages/plugins/trpc/src/zod/transformer.ts#L403-L421

**`fieldReference`**

![fieldReference](https://user-images.githubusercontent.com/51007475/230830007-21832aaa-ac55-4904-95a7-11d1e381d4b6.png)

This schema isn't generated at all, although there's an unmerged pull request that might provide some clues: https://github.com/Brettm12345/prisma-zod-generator/commit/8b1d50be7c82844bc8b1928d2cdf354461ed2ea6

**Environment (please complete the following information):**

-   ZenStack version: 1.0.0-alpha.98
-   Prisma version: 4.12.0
-   Database type: Postgres

**Additional context**

**Comment by ymc9** [comment]
Thanks for filing this @keanugrieves ! Yes, there're still several unresolved issues related to Prisma preview features. We should probably allocate the next iteration to focus on fixing them.
