### ISSUE TITLE
@@openapi.ignore() should generate schemas for relations

### ISSUE THREAD

**Issue by Azzerty23** [zenstackhq/zenstack#349]
**Description and expected behavior**
When using @@openapi.ignore() it omits generating paths but it should generate schema for relations.
E.g. AccountFindManyArgs (NextAuth) when creating a Post linked to an author (User model).

**Screenshots**
![Capture d’écran 2023-04-14 à 17 52 05](https://user-images.githubusercontent.com/43639468/232095024-bfc6a821-507f-42cc-9950-920d7455623e.png)

**Environment (please complete the following information):**

-   ZenStack version: 1.0.0-alpha.101
-   Prisma version: 4.12.0
-   Database type: SQLite

**Comment by ymc9** [comment]
Hi @Azzerty23 , this is fixed in the latest alpha.119 release.

Closed by #436 .
