### ISSUE TITLE
Bug with trpc plugin output when using non default schema location

### ISSUE THREAD

**Issue by Azzerty23** [zenstackhq/zenstack#378]
**Description and expected behavior**
After moving `*.zmodel` files to a new folder and updating the schema location in the generate command `npx zenstack generate --schema ./zmodels/schema.zmodel`, the trpc plugin generates output files (routers and schemas) in different folders than expected.

**Screenshots**
1. Moving .zmodel files to `zmodels/` folder
<img width="449" alt="Capture d’écran 2023-05-03 à 10 25 31" src="https://user-images.githubusercontent.com/43639468/235866877-4d6e1ac8-1066-4bfd-ac51-2e9073d65a1c.png">
2. trpc plugin output
<img width="275" alt="Capture d’écran 2023-05-03 à 10 24 40" src="https://user-images.githubusercontent.com/43639468/235866881-9124b1c6-9695-4448-9577-84592a1938e6.png">
3. Not consistency files location
<img width="467" alt="Capture d’écran 2023-05-03 à 10 24 26" src="https://user-images.githubusercontent.com/43639468/235866874-082950b5-f97a-4edc-9618-11142d6ccb75.png">

**Environment (please complete the following information):**

-   ZenStack version:  1.0.0-alpha.112
-   Prisma version: 4.12.0
-   Database type: SQLite

**Additional context**
Is the output option supposed to be relative to the location of `schema.zmodel` or to the location where `npx zenstack generate` is run? It might be useful to add this information to the documentation.

**Comment by ymc9** [comment]
Good point @Azzerty23 . I'll double check the plugin's behavior in terms of `output` and document it. Thanks!

**Comment by ymc9** [comment]
Hi @Azzerty23 , the output handling wasn't consistent in previous versions. In the latest alpha.119 release, all plugin's output path is unified to be relative to the location of ZModel. Please see if this aligns with your expectation. Thanks!

Fixed by #436
