### ISSUE TITLE
Support list and relation filters in auth policy

### ISSUE THREAD

**Issue by he-la** [zenstackhq/zenstack#393]
**Is your feature request related to a problem? Please describe.**
Reading through [how ZenStack works under the hood](https://zenstack.dev/docs/advanced/under-the-hood), it appears that the underlying implementation would support any prisma-supported filters for specifying access control rules. But this power isn't surfaced through the `@@allow` syntax - e.g. in the following schema, ZenStack doesn't appear to offer a way to restrict access to the shared cake to all its owners:

```
model User {
    id      String    @id @default(cuid())
    // ...
    cakes   Cake[]
}

model SliceOfCake {
    id        String    @id
    cake_id   String
    cake      Cake      @relation(fields: [cake_id], references: [id])
    owner_id  String
    owner     User      @relation(fields: [owner_id], references: [id])

    @@allow('all', auth() == owner)
}

model Cake {
    id      String
    slices  SliceOfCake[]

    @@allow('read', ??? how to allow owners of a slice to read the cake? )
}
```

**Describe the solution you'd like**
We want to generate the following condition on `Cake`:
```typescript
where: {
  slices: {
    some: {
      owner_id: user.id
    }
  }
}
```
which could be surfaced through `ZModel` through a mini DSL like
```
@@allow('read', slices.some.owner_id == auth().id)
```
(basically mapping directly to the underlying prisma filter, though it's somewhat dubious to have this ambiguity between field access on models vs. lists) or through a way to pass arbitrary strings through to the generated conditions.

**Describe alternatives you've considered**
Implement authorization in my application logic.

**Comment by ymc9** [comment]
Hey @he-la ,

I'm glad you found the under-the-hood article. Yes, ZModel should be able to express all filtering ability supported by Prisma.

For your specific case, there's an expression called [Collection Predicate](https://zenstack.dev/docs/reference/zmodel-language#collection-predicate-expressions). It allows you to traverse deep into related collections.

```prisma
    @@allow('read', slices?[owner == auth()])
```

Does this meet your needs? I think the documentation is buried too deep to be found ...

**Comment by he-la** [comment]
Ooh I missed that. Sorry and thanks!
