### ISSUE TITLE
Unable to set a default value for the Json field type

### ISSUE THREAD

**Issue by dariuspranskus** [zenstackhq/zenstack#416]
Hi 

I am unable to set a default value to a JSON type field.

It gives the syntax highlighting error in VS Code and also produces errors while generating.

It works fine in Prisma though.

**Screenshots**
![image](https://github.com/zenstackhq/zenstack/assets/15170614/c37d4f2b-1d7e-40ac-a6ef-1719e0a53c4e)
![image](https://github.com/zenstackhq/zenstack/assets/15170614/e0f68158-25e0-420f-bf9e-67b747107031)

**Environment (please complete the following information):**

-   ZenStack version: [e.g., 1.0.0-alpha.116]
-   Prisma version: [e.g., 4.14.0]
-   Database type: [e.g. Postgresql]

Is this a bug or there is another way how to escape the double quotes

Thanks

**Comment by ymc9** [comment]
Hey @dariuspranskus , right now string escaping is not properly implemented yet, but you can work around by mixing single and double quotes (single quote is also valid in ZModel) like:

```prisma
  settings Json? @default('{\\"foo\\": \\"bar\\"}')
```

Hope this helps and we'll fix the escaping issue soon.

**Comment by ymc9** [comment]
Fixed in [1.0.0-beta.21](https://github.com/zenstackhq/zenstack/releases/tag/v1.0.0-beta.21)
