### ISSUE TITLE
@zenstackhq/runtime can't install on docker container.

### ISSUE THREAD

**Issue by JYachelini** [zenstackhq/zenstack#417]
**Description and expected behavior**
I am trying to get my API up with the @zenstackhq/runtime package and when installing the dependencies in the docker container it runs out of memory. Trying different packages to find out which one was causing this, it turns out to be the one I mention.

**Screenshots**
<img width="333" alt="Captura de pantalla 2023-05-17 a la(s) 17 32 11" src="https://github.com/zenstackhq/zenstack/assets/77073866/c54edf57-dc2c-4913-8f38-d85b95ce70e6">
<img width="381" alt="Captura de pantalla 2023-05-17 a la(s) 17 32 26" src="https://github.com/zenstackhq/zenstack/assets/77073866/6b17bae5-d5b5-4fcf-92fe-87d65b650944">

Note: In my bitbucket-pipelines I increase the size of container with `size: 2x`

**Environment (please complete the following information):**
-  "@zenstackhq/runtime": "^1.0.0-alpha.116",

**Comment by ymc9** [comment]
This looks weird ... is it possible to share the docker file (or a simplified version)? 

You can find me on discord too: https://discord.com/invite/Ykhr738dUe and DM if it's more appropriate.

**Comment by JYachelini** [comment]
Sure, I will contact you from discord. Thanks!

**Comment by JYachelini** [comment]
Oh, @ymc9, can you generate new link? The link literally says can't accept the invitation

**Comment by ymc9** [comment]
Oops ... does this one work? https://discord.gg/qGqdkNBU

**Comment by ymc9** [comment]
Closing for now
