### ISSUE TITLE
Openapi plugin generates rest flavor specifications by default

### ISSUE THREAD

**Issue by Azzerty23** [zenstackhq/zenstack#437]
**Description and expected behavior**
Openapi plugin generates `rest` flavor specifications by default instead of `rpc` as described inside documentation.

**Screenshots**

**Environment (please complete the following information):**

-   ZenStack version: [e.g., 1.0.0-alpha.119]
-   Prisma version: [e.g., 4.14.0]
-   Database type: [e.g. Postgresql]

**Additional context**

**Comment by ymc9** [comment]
Good catch! And I've published a fix. Thank you @Azzerty23 !

**Comment by ymc9** [comment]
Fixed by #440
