### ISSUE TITLE
nextjs middleware issue while calling sequelize model into it 

### ISSUE THREAD

**Issue by Sanskar696** [zenstackhq/zenstack#443]
![image](https://github.com/zenstackhq/zenstack/assets/125652661/961f6e7d-e32b-4606-b6af-69b9170b2786)

Hey there @jonathangerbaud @jawadst @potion-cellar 
Facing an error while runing the api 

 wait compiling...
- warn ./node_modules/sequelize/lib/dialects/abstract/connection-manager.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/sequelize/lib/dialects/abstract/connection-manager.js
./node_modules/sequelize/lib/dialects/mariadb/connection-manager.js
./node_modules/sequelize/lib/dialects/mariadb/index.js
./node_modules/sequelize/lib/sequelize.js
./node_modules/sequelize/lib/index.js
./node_modules/sequelize/lib/index.mjs
./models/init_models.js

./node_modules/sequelize/lib/dialects/abstract/connection-manager.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/sequelize/lib/dialects/abstract/connection-manager.js
./node_modules/sequelize/lib/dialects/mariadb/connection-manager.js
./node_modules/sequelize/lib/dialects/mariadb/index.js
./node_modules/sequelize/lib/sequelize.js
./node_modules/sequelize/lib/index.js
./node_modules/sequelize/lib/index.mjs
./models/init_models.js
- error node_modules/sequelize/lib/utils/deprecations.js (34:0) @ <unknown>
- error (0 , import_util.deprecate) is not a function

**Comment by ymc9** [comment]
Hi @Sanskar696 , sorry I'm a bit confused. Is this related to a project using ZenStack?

**Comment by ymc9** [comment]
Closing for now.
