### ISSUE TITLE
Prisma roles server and client not works

### ISSUE THREAD

**Issue by liorFaigenzon** [zenstackhq/zenstack#463]
**Description and expected behavior**
CRUD not works by roles as followed by this page
https://zenstack.dev/docs/guides/understanding-access-policy
I added the role colum to user table and still getting an error p2004. Also I would like to know how to do a role based page desgin as the session not allow me to get the role as JWT not allow this.

Environment 

-   ZenStack version: 2.0.0
-   Prisma version: 4.10.0
-   Database type: mysql

**Comment by jiashengguo** [comment]
Is that possible for you can share your repo with me to identify the issue?  or simply the zmodel schema file if it’s easier for you.

You can get the user id from the JWT token, then use the client API to query the database to get the whole user instance to pass to the getEnhancedPrisma like below:
```ts
const user = await prisma.user.findUnique({
                where: { id: decoded.sub as string },
            });
const db = getEnhancedPrisma(user)
```

**Comment by liorFaigenzon** [comment]
I am not sure what you meant. If it is DB strategy  for the session. I have tried but got another error which I can share later.
The model is something like this:
@@allow('all', auth() == this)
model User {
    id String @id() @default(uuid())
    role String @default("user")
    createdAt DateTime @default(now())
    updatedAt DateTime @updatedAt()
    /// @email
    email String @unique()
    emailVerified DateTime?
    /// @password
    /// @omit
    password String?
    name String?
    spaces SpaceUser[]
    /// @url
    image String?
    lists List[]
    todos Todo[]
    accounts Account[]

    zenstack_guard Boolean @default(true)
    zenstack_transaction String?

    @@index([zenstack_transaction])
}

**Comment by jiashengguo** [comment]
Sorry that I don't get a clue with this piece of information. I guess it would be more efficient for me to identify the issue if you can share the complete repo with me.

**Comment by jiashengguo** [comment]
BTW, maybe you can refer to this repo about permission modeling:

https://github.com/ymc9/permission-modeling

**Comment by jiashengguo** [comment]
The problem has been fixed due to the extra role field needs to be added in NextAuth.

**Comment by liorFaigenzon** [comment]
May I suggest that this information be added into the tutorial or the project struct. As I am C# dinosaur  :)
