### ISSUE TITLE
[Feature Request] Nx  monorepo multiple app support

### ISSUE THREAD

**Issue by bphkns** [zenstackhq/zenstack#479]
**Is your feature request related to a problem? Please describe.**
I want to setup zenstack in nx mono repo for multiple nestjs app which have multiple prisma schema (app wise).

**Describe the solution you'd like**
Can we have a generator like[ nx-prisma](https://github.com/gperdomor/nx-tools/blob/main/packages/nx-prisma/README.md)

**Comment by ymc9** [comment]
Hi @bphkns , thanks for filing this! Yes, nx plugins are handy for initializing projects and running commands.

I'll keep it in the backlog and prioritize it with other requests. Let me know if you're interested in making a contribution, and I'll be happy to collaborate!

**Comment by ymc9** [comment]
The `zenstack generate` CLI now has a "--output" option for specifying default output dir. Closing for now.
