### ISSUE TITLE
Allow generating prisma schema without zenstack-specific fields and code

### ISSUE THREAD

**Issue by utomdht** [zenstackhq/zenstack#500]
**Is your feature request related to a problem? Please describe.**
I'm using prisma migrate without the client (as i'm not using nodejs), and would like to get the benefits from zmodel without the guard/transaction fields and code generation

**Describe the solution you'd like**
- Allow running generate without the default plugins
- add an option to @core/prisma to skip the additional guard and transaction fields

**Describe alternatives you've considered**
I'm currently using some other cli/vscode plugins, but they are missing some features like the model inheritance

**Additional context**

**Comment by ymc9** [comment]
Hi @utomdht , which version of ZenStack are you running now? With the latest version "beta.1", if your model doesn't contain any access policy (`@@allow`, `@@deny`), those fields shouldn't be generated.

**Comment by utomdht** [comment]
ah my bad, works well on the beta.1 version :+1: thanks !
