### ISSUE TITLE
Wrong hooks endpoints generated

### ISSUE THREAD

**Issue by potikhanovsergey** [zenstackhq/zenstack#501]
After I run "npm run generate" to auto-generate hooks, some of them are wrong, At the screenshot, the hook's endpoint should be /findFirst, but there's /findMany instead.  

**Screenshots**

Environment
-   ZenStack version: 1.0.0-beta.1
-   Prisma version: 4.14.0
-   Database type: sqlite

<img width="576" alt="image" src="https://github.com/zenstackhq/zenstack/assets/71494201/5fb7a712-8a83-4f93-a976-537371b744d7">

**Comment by ymc9** [comment]
Oops ... that's a bad mistake. Thanks for filing it @potikhanovsergey and my apologies for the carelessness. I'll push a fix today.

**Comment by ymc9** [comment]
Fixed in version "beta.2".
