### ISSUE TITLE
[Feature Request] Support returning "count" in RESTful API handler

### ISSUE THREAD

**Issue by ymc9** [zenstackhq/zenstack#527]
Getting the total count during pagination is a very common requirement. Since JSON:API allows custom meta, we can probably use it to contain that information in the response. Also, there should be an option to opt-in for this feature to avoid a default performance hit.

**Comment by chemitaxis** [comment]
hi @ymc9 I'm trying to build and test the project, but when I exec the` pnpm install` and `pnpm run build` I have some packages with error like this: 

![Screenshot 2023-06-30 at 19 06 05](https://github.com/zenstackhq/zenstack/assets/1420409/24f0ef7a-a1a4-40b2-b1df-5cb98aa3e942)

what i'm missing? thanks!

**Comment by chemitaxis** [comment]
hi @ymc9 can you please give access to make a PR? thanks :)

**Comment by ymc9** [comment]
Fixed by #529
