### ISSUE TITLE
Failed to check access policy for the connected model in implicit Many-to-Many relationship  

### ISSUE THREAD

**Issue by jiashengguo** [zenstackhq/zenstack#564]
``` prisma
model Post  {
    id String
    groups Group[]
    org Organization @relation(fields: [orgId], references: [id])
    orgId String
    @@allow('create', owner == auth() && org.members?[this == auth()])
}

model Group{ 
    id String
    org Organization @relation(fields: [orgId], references: [id])
    orgId String

    @@allow('all', org.members?[auth() == this])
}
```

In the `create` operation of `Post`,  it should also check the `read` and `update` policy of `Group`.  

Now,  it didn't run any checks which causes I can create a post to connect to Group in another org that I don't belong to.

**Comment by ymc9** [comment]
Connecting models with many-to-many relationship is now tightened up, the model being connected needs to pass "update" check.
