### ISSUE TITLE
 [Feature request] Support implicit inversed relationship

### ISSUE THREAD

**Issue by jiashengguo** [zenstackhq/zenstack#613]
Support the below schema:

```prisma
model User {
  id    Int    @id @default(autoincrement())
 // posts Post[].    no need to specify it in Zmodel,  ZenStack will generate it in the schema.prisma file.
}

model Post {
  id       Int  @id @default(autoincrement())
  author   User @relation(fields: [authorId], references: [id])
  authorId Int
}
```

Need naming convention rule to generate the inversed relation.  Also, need a way to distinguish between one-to-one and one-to-many.   

Take a reference of how EF handles it:
https://learn.microsoft.com/en-us/ef/core/modeling/relationships/one-to-one#one-to-one-without-navigation-to-dependent

**Comment by jmarbutt** [comment]
This would dramatically improve cases like this where it large schemas reference a common table like `User`

**Comment by ymc9** [comment]
Closing as it's covered by #430
