### ISSUE TITLE
npx zenstack generate fails to run Prisma plugin on Windows 10 only

### ISSUE THREAD

**Issue by SadmanYasar** [zenstackhq/zenstack#614]
This is the repository where I am using Zenstack: https://github.com/SadmanYasar/proptory-webapp-nextjs

After running npx zenstack generate, I get the following:
```
⌛️ ZenStack CLI v1.0.0-beta.13, running plugins
⠋ Running plugin PrismaEnvironment variables loaded from .env
Error: Provided --schema at C:\\Users\\PC\\Desktop\\Web doesn't exist.
✖ Running plugin Prisma
Prisma: Failed to run "prisma generate"
```

Running  ```npx prisma generate``` separately works fine. This issue is resolved when I ran this repository on Github Codespaces with Ubuntu.

**Environment**

-   ZenStack version: v1.0.0-beta.13
-   Prisma version: ^5.0.0
-   Database type: Postgresql

**Additional context**
Problem only exists on Windows 10

**Comment by ymc9** [comment]
Thanks for the repro project @SadmanYasar !

@jiashengguo , could you help take a look into this?

**Comment by ymc9** [comment]
Closing for now
