### ISSUE TITLE
TRPC generator doesn't generates count method

### ISSUE THREAD

**Issue by mildlysupreme** [zenstackhq/zenstack#618]
Hi! Thank you for awesome software!  For some reason TRPC generator doesn't generates count method

![image](https://github.com/zenstackhq/zenstack/assets/132460323/2067caf0-ee05-4a66-b532-79ad408c5a26)

-   ZenStack version: 1.0.0-beta.11
-   Prisma version: 5.0.0
-   Database type: Postgres

**Comment by ymc9** [comment]
Hey @mildlysupreme , thanks for reporting this. This is caused by incomplete schema metadata provided by Prisma 😂 - the "count" operation and related structure is missing there. We'll need to patch it somehow.

**Comment by imsanchez** [comment]
Thank you for reporting @mildlysupreme! 

Issue tracked via https://github.com/omar-dulaimi/prisma-trpc-generator/issues/81

**Comment by ymc9** [comment]
Fixed in [1.0.0-beta.21](https://github.com/zenstackhq/zenstack/releases/tag/v1.0.0-beta.21)
