### ISSUE TITLE
Zod generation error after Prisma upgrade

### ISSUE THREAD

**Issue by mbrimmer83** [zenstackhq/zenstack#621]
I get a several of these errors after upgrading Prisma
```
node_modules/.zenstack/zod/objects/ActionGroupCountOutputTypeArgs.schema.ts:9:42 - error TS2724: '"/node_modules/.prisma/client/index".Prisma' has no exported member named 'ActionGroupCountOutputTypeArgs'. Did you mean 'ActionGroupCountOutputType'?
9 type SchemaType = z.ZodType<Purge<Prisma.ActionGroupCountOutputTypeArgs>>;
```

**Environment (please complete the following information):**

-   ZenStack version: 1.0.0-beta.16
-   Prisma version: 5.1.1
-   Database type: cockroachdb

**Additional context**
The problem goes away when I reverted prisma to 5.0.0.

**Comment by ymc9** [comment]
Hey @mbrimmer83 , thanks for reporting, and I just noticed the same issue ... It seems Prisma has been making frequent changes to the generated public types ... I'll add some compatibility code first and see Prisma folks' advice on the best way to stay safe.

**Comment by ymc9** [comment]
Just noticed other projects also got broken with 5.1.1. I'm holding off adding compatibility fixes and will wait for suggestions from Prisma side a bit.

**Comment by ymc9** [comment]
Prisma has confirmed the issue and will add a type alias for backward compatibility.
https://github.com/prisma/prisma/issues/20614

**Comment by ymc9** [comment]
Hi @mbrimmer83 , Prisma 5.2 is released and it seems the problem has been fixed. Could you upgrade and give it a try?

**Comment by mbrimmer83** [comment]
> Hi @mbrimmer83 , Prisma 5.2 is released and it seems the problem has been fixed. Could you upgrade and give it a try?

Yes, i'll upgrade tonight and let you know

**Comment by mbrimmer83** [comment]
Everything appears to be working for me with Zenstack `v1.0.0-beta.20` and Prisma v5.2.0`

**Comment by mbrimmer83** [comment]
This issue can be resolved by upgrading Prisma to `v5.2.0`.

**Comment by ymc9** [comment]
Thank you for the confirmation @mbrimmer83 !

**Comment by platon-ivanov** [comment]
Hello! I am getting the same error when using with TRPC.

**Environment:**

- @zenstackhq/runtime: 1.1.1,
- @zenstackhq/trpc: 1.1.1,
- zenstack: 1.1.1,
- prisma: 5.5.2.
