### ISSUE TITLE
Zod generation fails when previewFeatures = ["fullTextSearch"]

### ISSUE THREAD

**Issue by mateus-p** [zenstackhq/zenstack#650]
**Description and expected behavior**
Zod does not generate the "[...]OrderByWithRelationInput.schema" (but tries to import it) when Full Text Search is activated.
It seems like Prisma generates a OrderByWithRelationInput type in order to Full Text Search work, but '@core/zod' cannot handle that correctly.

**Screenshots**
![image](https://github.com/zenstackhq/zenstack/assets/56934662/5fe7abb5-1a23-4ec7-97dd-8754e03efba8)
![image](https://github.com/zenstackhq/zenstack/assets/56934662/3ad85e5d-ba5f-45af-8f13-38d0d414225e)

**Environment:**

-   ZenStack version: 1.0.0-beta.20
-   Prisma version: 5.2.0
-   Database type: Postgresql

**Comment by ymc9** [comment]
Thanks for filing this @mateus-p . When full-text search is enabled, the reference to OrderByXXX schema needs to use a variant name. I'll fix it in the next release.

**Comment by ymc9** [comment]
Fixed in [1.0.0-beta.21](https://github.com/zenstackhq/zenstack/releases/tag/v1.0.0-beta.21)
