### ISSUE TITLE
[Doc] NestJS guide

### ISSUE THREAD

**Issue by ymc9** [zenstackhq/zenstack#656]

**Comment by greedy-brady** [comment]
Hello :) Is There no plan to write nestJs doc?
or Just I do with nestjs ?

**Comment by ymc9** [comment]
> Hello :) Is There no plan to write nestJs doc? or Just I do with nestjs ?

Hi @greedy-brady , we don't have a guide yet but we do have something very close 😄:

https://zenstack.dev/blog/nest-api
