### ISSUE TITLE
Extend zenstack numeric functions to decimal

### ISSUE THREAD

**Issue by sitch** [zenstackhq/zenstack#657]
These https://zenstack.dev/docs/reference/zmodel-language#number should apply to `Int`, `Float`, and `Decimal`.

**Example:**

```prisma
model Example {
  decimalNumber Decimal @gt(0) // doesn't work
}

```

**Comment by ymc9** [comment]
Fixed in [1.0.0-beta.21](https://github.com/zenstackhq/zenstack/releases/tag/v1.0.0-beta.21)
