### ISSUE TITLE
[Feature Request] Make Zmodel color schema looks cool and consistent

### ISSUE THREAD

**Issue by jiashengguo** [zenstackhq/zenstack#716]
Currently, in some color themes, the Zmodel schema looks 'empty' and quite different with prisma and the ts file:

![image](https://github.com/zenstackhq/zenstack/assets/16688722/1bdfea59-7547-441d-8d75-b359651d23cf)

**Comment by Jonatthu** [comment]
@jiashengguo do we know if this is going to be released?

**Comment by jiashengguo** [comment]
@Jonatthu  Sorry for the late response. I think it would be included in the v1.1 release within this month.

**Comment by martzoukos** [comment]
I'm also looking forward to this. Replacing the schema.prisma with schema.zmodel file creates the expectation to the users that they would interact with it the same way.

Keep up the great work!
