### ISSUE TITLE
Autogenerated CRUD API should omit Id fields for adding new entities by POST

### ISSUE THREAD

**Issue by vbg8exadel** [zenstackhq/zenstack#736]
**Description and expected behavior**
I used to use Spring Data Rest which does generate the CRUD API out of managed entity classes. They correctly omit Id fields from POST operations where we add new entity to the DB. The Id is autogenerated either by DB or by the framework code. Therefore, the API should not ask for the Id to be provided as part of the request.

**Screenshots**
Here is a typical example:
![image](https://github.com/zenstackhq/zenstack/assets/145759001/dd1b1a2c-149d-4e8a-9157-da219851ff9d)

**Environment (please complete the following information):**

-   ZenStack version: 1.0.2
-   Prisma version: 5.3.1
-   Database type: Postgresql

**Additional context**
Even though the Id marked as required in the Open API, actual `POST /entity` doesn't fail for request without Id, which is correct.

**Comment by ymc9** [comment]
Thanks for filing this @vbg8exadel ! I'm marking it to be fixed in V1.1

**Comment by ymc9** [comment]
Fixed in v1.1.0.
