### ISSUE TITLE
zmodel schema validation key names: string and int

### ISSUE THREAD

**Issue by umdstu** [zenstackhq/zenstack#744]
**Description and expected behavior**
I'm trying to create a plugin similar to the `@zenstackhq/openapi` plugin. When I'm passing the meta object to the plugin in an object, I appear to be limited in key name types. Unlike others that ran into reserved word issues, this is much more general. The validator rejects key names if they are ints, strings, dashes, or start with $.  I'm using strings because int's and dashes aren't valid keys.

**Screenshots**
<img width="574" alt="Screenshot 2023-10-09 at 8 55 23 AM" src="https://github.com/zenstackhq/zenstack/assets/1298036/be28fb1a-28c4-48b1-8155-5ad2524e64cf">

**Environment (please complete the following information):**

-   ZenStack version: 1.0.2
-   Prisma version: 4.16.2
-   Database type: Postgresql

**Comment by ymc9** [comment]
Hey @umdstu , thanks for reporting this! Do you mind sharing the openapi plugin code snippet?

**Comment by umdstu** [comment]
I'll grab it when I'm back online, but I just wanted to be clear that this is for a new plugin I'm writing to extend the openapi plugin, that needs to be able to pass in openapi extension style keys (https://swagger.io/docs/specification/openapi-extensions/), e.g. `x-api-gateway`.

The issue is the zmodel validator rejects quoted key values. So put any quoted key value pair in any plugin config and it'll cry.

**Comment by ymc9** [comment]
Got it. I think this information is enough for me to get going. I'll let you know is more is needed.

**Comment by ymc9** [comment]
> I'll grab it when I'm back online, but I just wanted to be clear that this is for a new plugin I'm writing to extend the openapi plugin, that needs to be able to pass in openapi extension style keys (https://swagger.io/docs/specification/openapi-extensions/), e.g. `x-api-gateway`.
> 
> The issue is the zmodel validator rejects quoted key values. So put any quoted key value pair in any plugin meta and it'll cry.
> 
> E.g
> 
> ```
> @@openapi.meta({
>     "x-api": {}
> })
> ```

Hi @umdstu , the latest 1.1.0 release supports using string literals as object keys. Could you give it a try? Thanks!

**Comment by umdstu** [comment]
Hey @ymc9 ! Thanks for the quick turn around on this. Sorry for the delay in responding. I just pulled in v1.1.0 for all of the packages, and after reloading vscode I'm getting no validation errors for quoted string keys! 

I am unsure what the state of numbers as keys is supposed to be though. I noticed in your MR that you added what appeared to be support for numbers as keys (`NumberLiteral`), but wasn't sure exactly what was going on there. Using `200` as a key still does not validate though, e.g.:
```
@@plugin.meta({
    200: {
        response: ""
    }
```

Thank you again!

**Comment by ymc9** [comment]
> Hey @ymc9 ! Thanks for the quick turn around on this. Sorry for the delay in responding. I just pulled in v1.1.0 for all of the packages, and after reloading vscode I'm getting no validation errors for quoted string keys!
> 
> I am unsure what the state of numbers as keys is supposed to be though. I noticed in your MR that you added what appeared to be support for numbers as keys (`NumberLiteral`), but wasn't sure exactly what was going on there. Using `200` as a key still does not validate though, e.g.:
> 
> ```
> @@plugin.meta({
>     200: {
>         response: ""
>     }
> ```
> 
> Thank you again!

Hi @umdstu , you're welcome! The change only added support for using string literals as object keys, but not numeric values. I refrained to add that since most languages don't seem to support it and it may cause ambiguity with array access.

I'm not sure about the exact scenario of your plugin. Is it possible to detect the key (string or numeric string) and process accordingly?

**Comment by umdstu** [comment]
You're absolutely correct, sorry about that.  I think I was only trying to use a number because the string versions weren't working. Just ignore me :)

Thank you again!
