### ISSUE TITLE
`prisma not found, please install it`

### ISSUE THREAD

**Issue by justinTM** [zenstackhq/zenstack#773]
hey all!

prisma is definitely installed but `npx zenstack generate` can't find it :/

reproduce:
```console
$ npm install prisma -g
$ npx zenstack generate
prisma not found, please install it
$ prisma --version
<version output>
```

**Comment by ymc9** [comment]
> hey all!
> 
> prisma is definitely installed but `npx zenstack generate` can't find it :/
> 
> reproduce:
> 
> ```
> $ npm install prisma -g
> $ npx zenstack generate
> prisma not found, please install it
> $ prisma --version
> <version output>
> ```

Hy @justinTM , could you run `npx zenstack -v` and see what version you're on?

**Comment by ymc9** [comment]
Closing for now. Please reactivate if the issue persists.

**Comment by quinnvaughn** [comment]
Having the same issue with yarn v4. I have 1.10.0 installed.

**Comment by quinnvaughn** [comment]
With yarn v1 I have no problems.
