### ISSUE TITLE
[BUG] PolicyUtils.reduce() does not account for NOT values which are Arrays instead of Objects

### ISSUE THREAD

**Issue by jasonmacdonald** [zenstackhq/zenstack#807]
**Description and expected behavior**
When providing a `where` condition containing `NOT`,  the `NOT` condition must be an Object; otherwise, the reduce function will improperly convert the Array index values into Object keys.

Example:  _(this is a simplistic example, our specific condition was much larger)_
```
{
    "where": {
        "NOT": [
            {
                "id": {
                    "equals": 1
                },
                "isDeleted": {
                    "equals": false
                }
            }
        ]
    }
}
```

This will fail because it converts the array indexes to Object keys '1', and '2' on `NOT` which Prisma cannot find.

**Environment (please complete the following information):**

-   ZenStack version: 1.2.0
-   Prisma version: 5.5.2
-   Database type:  Postgresql

**Comment by jasonmacdonald** [comment]
I'll see about providing a fix when I can find a few minutes. For now, changing our code to not use an Array when dealing with `NOT` is the short-term workaround.

**Comment by ymc9** [comment]
Thanks for filing this @jasonmacdonald ! Please let me know if you need any support on the fix.

**Comment by ymc9** [comment]
Hi @jasonmacdonald , I'm still having trouble reproducing this issue. Could you give a bit more context about your usage? Thank you!

**Comment by jasonmacdonald** [comment]
> Hi @jasonmacdonald , I'm still having trouble reproducing this issue. Could you give a bit more context about your usage? Thank you!

Sorry, I missed your reply here. 

The root issue appears to have been fixed in a later update from when I posted this (v1.2.0). Looking back at the code from version 1.2.0, this line https://github.com/zenstackhq/zenstack/blob/v1.2.0/packages/runtime/src/enhancements/policy/policy-utils.ts#L187 was causing the issue where `not` was assuming the result was always an Object, and converting any Array index into an Object key, which results in an error as `[0]` was not a valid key on the Object in the example I gave.

 However, looking at the last version https://github.com/zenstackhq/zenstack/blob/v1.3.0/packages/runtime/src/enhancements/policy/policy-utils.ts#L192, this appears to have been update, so I think you can probably close this. :)
