### ISSUE TITLE
[Feature] Adding support for Zod schemas for dates with `coerce` option in the `schema.zmodel` file of the Zod plugin

### ISSUE THREAD

**Issue by kpidoff** [zenstackhq/zenstack#824]
**Description:**
Currently, the Zod plugin does not support handling Zod schemas for dates with the `coerce` option in the `schema.zmodel` file. This feature would be very useful to simplify date validation when defining Zod schemas.

**Request:**
I would like to make a request to add the ability to handle Zod schemas for dates with the `coerce` option in the `schema.zmodel` file. The idea is to allow users to specify `coerce: true` when defining a date schema, which would make date validation and conversion easier.

**Code Example:**
Here is an example of what defining a date schema with the `coerce` option in the `schema.zmodel` file could look like:

```
plugin zod {
  provider = '@core/zod'
  output = 'src/lib/zod'
  compile = false
  modelOnly = true
  coerce = true
};

```
**Impact:**
This feature would enhance the flexibility and user-friendliness of the Zod plugin by enabling developers to more easily manage date schemas with a coerce option.

Thank you for considering this request.

**Comment by ymc9** [comment]
Thanks for proposing this @kpidoff . When "coerce" is enabled, the zod schema generated for all primitive fields will have "z.coerce", right?

**Comment by kpidoff** [comment]
Yes, especially for the management of dates.

**Comment by ymc9** [comment]
> Yes, especially for the management of dates.
> 
> ```
> const baseSchema = z.object({
>     id: z.string(),
>     start: z.coerce.date(),
>     end: z.coerce.date(),
>     sellingPrice: z.number().nullish(),
>     startupPrice: z.number().nullish(),
>     receptionPrice: z.number().nullish(),
> });
> ```

Got it. The feature can probably combine a "coerce = true" plugin option for global settings and a "@coerce" attribute for field-level override.

I guess this is not blocking, right?

**Comment by kpidoff** [comment]
es, exactly, the '@Coerce' attribute can definitely be considered and is much more configurable, good insight.

**Comment by ymc9** [comment]
`coerce()` call is generated for DateTime field automatically in latest release. Closing for now.

**Comment by MaxmaxmaximusFree** [comment]
you need to add the @coerce directive not only for Date, it is obvious that it is needed for any field. For example, for Int
