### ISSUE TITLE
RESTful API handler should avoid using mode: 'insensitive' on SQL Server

### ISSUE THREAD

**Issue by elsantoalcielo** [zenstackhq/zenstack#841]
I am using ZenStack's Express middleware to serve a REST API with an SQL Server as database. When I try to use a `contains` filter, as in
```
http://192.168.1.14:3000/api/gPW_formulations?filter[name$icontains]=sometext
```
the Prisma client returns the following error:

![image](https://github.com/zenstackhq/zenstack/assets/10650342/fc9d7092-c98e-4e4f-a188-96213ff44d03)

Indeed, the Prisma documentation states that you can't use `mode: 'insensitive'` on SQL Server:

> Microsoft SQL Server uses case-insensitive collation by default. Therefore, filtering with Prisma Client and Microsoft SQL Server is case-insensitive by default.
> 
> mode: 'insensitive' property is not required and therefore not available in the generated Prisma Client API.
> 

https://www.prisma.io/docs/concepts/components/prisma-client/case-sensitivity#microsoft-sql-server-provider

What I'm using:

-   ZenStack version: 1.3.0
-   Prisma version: 5.6.0
-   Database type: SQL Server

**Comment by ymc9** [comment]
Thanks for catching this @elsantoalcielo . For case-senstive filter you can use the "$contains" operator. Currently, the API handlers don't know what database is used so don't have a good way to reject queries that are actually not supported ...

**Comment by ymc9** [comment]
Closing for now due to no follow up.
