### ISSUE TITLE
[Feature Request] TRPC 11 support

### ISSUE THREAD

**Issue by ymc9** [zenstackhq/zenstack#859]

**Comment by DawidWraga** [comment]
yes! I want to use react query v5. But react query v5 is not compatible with trpc v10. So I need to use trpc v11... which is not compatible with zenstack v1.5! Any plans for when we might see this available?

**Comment by ymc9** [comment]
> yes! I want to use react query v5. But react query v5 is not compatible with trpc v10. So I need to use trpc v11... which is not compatible with zenstack v1.5! Any plans for when we might see this available?

Hi @DawidWraga , I haven't tried V11 yet, so not sure how much change is needed. Have you already upgraded your project? What are the main differences that you notice?

**Comment by ymc9** [comment]
Having a conversation with trpc maintainers here: https://discord.com/channels/867764511159091230/1200854658915242004

**Comment by ymc9** [comment]
> Hi! has there been any update on this feature request? Is this fixed in v2?

Not yet. It was blocked by a typing breaking change on tRPC side. Let me check with their folks and see if it's resolved.

**Comment by ymc9** [comment]
Created a new thread on trpc's dicord: https://discord.com/channels/867764511159091230/1266837300235735070

**Comment by ymc9** [comment]
Fixed in 2.5.0
