### ISSUE TITLE
[Bug] Zod Plugin Default Values

### ISSUE THREAD

**Issue by sakgoyal** [zenstackhq/zenstack#886]
**Description and expected behavior**
Setting default values and using the Zod plugin does not generate types with default values. 

**Screenshots**
![image](https://github.com/zenstackhq/zenstack/assets/19929553/dc2c12c4-9ec5-4d27-8531-a52fdde5c0d7)
![image](https://github.com/zenstackhq/zenstack/assets/19929553/cffa34aa-bac7-465a-9d63-be62fbf8f6c7)

default values for empty strings are missing. 
**Environment (please complete the following information):**

-   ZenStack version: `1.4.1`
-   Prisma version: `5.6.0`
-   Database type: `Postgresql`

**Comment by ymc9** [comment]
Good catch @sakgoyal ! Right now default values are not handled during Zod generation. We should at least do it for literal default values.

How important is this to you now?

**Comment by sakgoyal** [comment]
I am currently slowly adopting zenstack from regular prisma so its not immediately nessesary, but it would be ideal to have this done within a month. but I understand if that is not possible

**Comment by ymc9** [comment]
Got it @sakgoyal . Let's aim for the end of the year, then. Let me know if you're interested in working on a PR, and I'll be glad to facilitate 😄.
