### ISSUE TITLE
Access Policy doesn't work properly

### ISSUE THREAD

**Issue by serusko** [zenstackhq/zenstack#887]
**Description and expected behavior**
A clear and concise description of what the bug is and what's the expected behavior.

I have a problem with Access Policy, its working for exact ID = 2, and not working for anything else. so if I even hardcode `enhance(prisma, { user: { id: 3 } }`  I cannot get any results, only for ID = 2

**Screenshots**

I have 2 models, User and Dog, and I want to disable read Dog entities for rest of users, so just "owner" can see his dogs

```

model User {
  id Int @id @default(autoincrement())
  email String @unique
  name String
  createdAt DateTime @default(now())
  modifiedAt DateTime? @updatedAt
  role String
  dogs Dog[]

  @@allow("read", true)
  @@deny("update", true)
}

model Dog {
  id Int @id @default(autoincrement())
  user User @relation(fields: [userId], references: [id])
  userId Int @omit
  name String
  @@allow("read", auth().id == userId)
}
```

**Environment (please complete the following information):**

-   ZenStack version: 1.4.1
-   Prisma version: 5.7.0
-   Database type: Postgresql

**Additional context**

Thank you for your response

**Comment by ymc9** [comment]
Hi @serusko , thanks for creating this issue.

Could you show the Prisma query and the data in the database? If you create the enhanced prisma client with `{ user: { id: 3 } }`, according to your rules in `Dog`, when you call `finding` it should only give you back rows of `Dog` with `userId == 3`.

**Comment by serusko** [comment]
omg I am so sorry, I spent 3 days playing around and I get stucked with forgotten hardcoded value deeper inside service 
Also my personal curse is that I will find the cause of the error as soon as I ask someone else about it :D
(I am also new to nest so it was tricky to make it work properly with DI and extending prisma service based on request), 
thank you for your work and effort, this tool looks promising :heart:

**Comment by ymc9** [comment]
> Also my personal curse is that I will find the cause of the error as soon as I ask someone else about it :D

No worries. That's how rubber ducks work 😄. I'm glad you find Zenstack helpful!
