### ISSUE TITLE
User context does not have field "clerkUserId" used in policy rules

### ISSUE THREAD

**Issue by sakgoyal** [zenstackhq/zenstack#909]
**Description and expected behavior**
I am having trouble setting this up and im not exactly sure what this error means. 
I get this when I access `/api/model/users/2`
![image](https://github.com/zenstackhq/zenstack/assets/19929553/c7e1db2e-586a-4d93-8250-193831d355c8)

zmodel:
```
abstract model Core {
    id Int @id @default(autoincrement())
	...
}
model User extends Core {
    clerkUserId String? @unique
	...

    // author has full access
    @@allow('all', auth() != null && auth().clerkUserId == clerkUserId)
```

```ts
// src/api/model/[...path].ts
import type { NextApiRequest } from 'next';
import { enhance } from '@zenstackhq/runtime';
import { getAuth } from '@clerk/nextjs/server';
import { DB } from '@app/server/Service/DatabaseService';
import { NextRequestHandler } from '@zenstackhq/server/next';
import RestApiHandler from '@zenstackhq/server/api/rest';

async function getPrisma(req : NextApiRequest) {
    const auth = getAuth(req);
    return enhance(DB, { user : auth ? { id : auth.userId } : undefined });
};

export default NextRequestHandler({getPrisma, handler : RestApiHandler({endpoint : 'http://localhost:3000/api/model'})});

```

**Environment (please complete the following information):**

-   ZenStack version: `1.5.0`
-   Prisma version: `5.6.0`
-   Database type: `Postgresql`

**Additional context**
clerkUserId is where I store the id returned from clerk. the id field is just autoincremented value so I do not want to use that. the clerkUserId is also a string which I do not know how to handle here
the rest api is working as intended for now (I have everything allowed if you're signed in without checking the clerkId)

**Comment by ymc9** [comment]
Hi @sakgoyal ,

The `user` field that you passed to the `enhance` API as part of the context provides value for the `auth()` function call in ZModel. So if you access `auth().clerkUserId` in the rules, you need to include it in the context.

You can try changing the `enhance` call to:

```ts
const auth = getAuth(req);
const user = auth ? 
    (await prisma.user.findUnique({
        where: { clerkUserId: auth.userId },
        select: { id: true, clerkUserId: true } 
    }))
    : undefined;
return enhance(DB, { user });
```

This part of the documentation provides more details about it: https://zenstack.dev/docs/the-complete-guide/part1/access-policy/current-user

**Comment by sakgoyal** [comment]
perfect. thank you

**Comment by devhero** [comment]
Using 'repl' I have the same issue, is it possible to override the enhance function inside repl?

**Comment by ymc9** [comment]
Hi @devhero , in "repl" you can use the ".auth" command to configure a user object, which will be passed to `enhance` as the context. Have you tried that?

**Comment by devhero** [comment]
Hi @ymc9, yes I used the .auth command, I was in search for an method to load relational data I used with User model but I think it's out of scope.
Anyway zenstack is a great framework and REPL is a life saver :+1:
